#  Análisis de Datos — Total Automotriz La Victoria

**Datos:** Sep 2023 → Sep 2025 (2 años de operación)  
**Objetivo:** Entender qué productos vender, cuáles rotan más, márgenes y tendencias  
**Herramientas:** pandas, numpy, matplotlib, seaborn

---

In [4]:

# ══════════════════════════════════════════════════
# Estas son las librerías son las que vamos a utilizar.

import pandas as pd          # Manejo de datos (tablas/DataFrames)
import numpy as np           # Cálculos matemáticos y estadísticas
import matplotlib.pyplot as plt  # Gráficas base
import seaborn as sns        # Gráficas más bonitas sobre matplotlib
import warnings
warnings.filterwarnings('ignore')

# Configuración visual
plt.rcParams['figure.figsize'] = (14, 5)
sns.set_theme(style="whitegrid")

# Colores del negocio
COLOR_NAVY = '#1B2A4A'
COLOR_GOLD = '#D4AF37'

print(" Librerías cargadas correctamente")
print(f"   pandas  versión: {pd.__version__}")
print(f"   numpy   versión: {np.__version__}")

 Librerías cargadas correctamente
   pandas  versión: 2.2.3
   numpy   versión: 2.1.3

In [5]:
# ══════════════════════════════════════════════════
# CELDA 3 — CARGAR EL ARCHIVO EXCEL
# ══════════════════════════════════════════════════

ARCHIVO = r"F:\ANALISIS DATOS TOTAL AUTOMOTRIZ.xlsx"

# Cargar cada hoja en su propio DataFrame
df_facturas      = pd.read_excel(ARCHIVO, sheet_name='FACTURAS 20-09-2023-20-09-2025')
df_articulos     = pd.read_excel(ARCHIVO, sheet_name='ARTICULOS ')
df_clientes      = pd.read_excel(ARCHIVO, sheet_name='CLIENTES')
df_departamentos = pd.read_excel(ARCHIVO, sheet_name='DEPARTAMENTOS')
df_proveedores   = pd.read_excel(ARCHIVO, sheet_name='PROVEEDORES')

print(" Archivo cargado exitosamente!\n")
print(f"{'Hoja':<30} {'Filas':>8}  {'Columnas':>9}")
print("-" * 50)
for nombre, df in [
    ('FACTURAS',      df_facturas),
    ('ARTICULOS',     df_articulos),
    ('CLIENTES',      df_clientes),
    ('DEPARTAMENTOS', df_departamentos),
    ('PROVEEDORES',   df_proveedores),
]:
    print(f"{nombre:<30} {len(df):>8,}  {len(df.columns):>9}")

 Archivo cargado exitosamente!

Hoja                              Filas   Columnas
--------------------------------------------------
FACTURAS                         21,928          7
ARTICULOS                        10,120         14
CLIENTES                            735         13
DEPARTAMENTOS                        37          2
PROVEEDORES                         282         13

In [7]:
# ══ — EXPLORACIÓN INICIAL
# Lo PRIMERO en cualquier proyecto de datos:
# entender QUÉ tenés antes de analizar.
# ══════════════════════════════════════════════════

print("=" * 55)
print("  EXPLORANDO: FACTURAS")
print("=" * 55)

# .shape → filas y columnas
print(f"\n Tamaño: {df_facturas.shape[0]:,} filas × {df_facturas.shape[1]} columnas")

# .columns → nombres de columnas
print(f"\n Columnas:\n  {df_facturas.columns.tolist()}")

# .head() → primeras filas (siempre al final de la celda
#            para que Jupyter lo muestre bonito)
print("\n Primeras 5 filas:")
df_facturas.head()

=======================================================
  EXPLORANDO: FACTURAS
=======================================================

 Tamaño: 21,928 filas × 7 columnas

 Columnas:
  ['No.factura', 'Nombre cliente', 'Fecha', 'Tipo factura', 'Saldo capital', 'Vendedor', 'Abono']

 Primeras 5 filas:

,No.factura,Nombre cliente,Fecha,Tipo factura,Saldo capital,Vendedor,Abono
0,40497,jose,2025-09-20,Contado,3500.0,Andrew Chamorro,0.0
1,2310-B,OSCAR,2025-09-20,Contado,1600.0,Alex Chamorro,0.0
2,2309-B,ROY,2025-09-20,Contado,1200.0,Alex Chamorro,0.0
3,40496,ROY,2025-09-20,Contado,4700.0,Alex Chamorro,0.0
4,40495,ROY,2025-09-20,Contado,0.0,Charlie Marenco Chamorro,0.0

In [8]:
# ═════════════════— TIPOS DE DATOS Y VALORES NULOS
# ══════════════════════════════════════════════════
# Antes de analizar CUALQUIER dato, hay que verificar:
# 1. ¿Cada columna tiene el tipo correcto?
# 2. ¿Hay datos faltantes (nulos)?

print(" TIPOS DE DATOS ACTUALES:")
print("-" * 35)
print(df_facturas.dtypes)

print("\n\n  VALORES NULOS POR COLUMNA:")
print("-" * 35)
nulos = df_facturas.isnull().sum()
pct   = (nulos / len(df_facturas) * 100).round(1)
resumen = pd.DataFrame({
    'Nulos':        nulos,
    'Porcentaje %': pct
})
print(resumen)

print("\n\n INTERPRETACIÓN:")
print(f"   Columnas sin ningún nulo:    {(nulos == 0).sum()}")
print(f"   Columnas CON algún nulo:     {(nulos > 0).sum()}")
print(f"\n     'Saldo capital' tiene tipo: {df_facturas['Saldo capital'].dtype}")
print(f"     'Fecha' tiene tipo:          {df_facturas['Fecha'].dtype}")
print("\n   → Si Fecha no dice datetime64, hay que convertirla")
print("   → Si Saldo capital no dice float64, hay que convertirlo")
print("   → Eso lo hacemos en la siguiente celda: LIMPIEZA")

 TIPOS DE DATOS ACTUALES:
-----------------------------------
No.factura                object
Nombre cliente            object
Fecha             datetime64[ns]
Tipo factura              object
Saldo capital            float64
Vendedor                  object
Abono                    float64
dtype: object


  VALORES NULOS POR COLUMNA:
-----------------------------------
                Nulos  Porcentaje %
No.factura          1           0.0
Nombre cliente      1           0.0
Fecha               1           0.0
Tipo factura        1           0.0
Saldo capital       1           0.0
Vendedor          880           4.0
Abono               1           0.0


 INTERPRETACIÓN:
   Columnas sin ningún nulo:    0
   Columnas CON algún nulo:     7

     'Saldo capital' tiene tipo: float64
     'Fecha' tiene tipo:          datetime64[ns]

   → Si Fecha no dice datetime64, hay que convertirla
   → Si Saldo capital no dice float64, hay que convertirlo
   → Eso lo hacemos en la siguiente celda: LIMPIEZA

In [9]:
# ════════LIMPIEZA DE DATOS
# Antes de analizar, los datos tienen que estar
# en el formato correcto. Esto se llama "cleaning".
# ══════

# Renombrar columnas para trabajar más fácil
df_facturas.columns = ['factura_id', 'cliente', 'fecha', 
                        'tipo', 'total', 'vendedor', 'abono']

# Convertir fecha al tipo correcto (datetime)
df_facturas['fecha'] = pd.to_datetime(df_facturas['fecha'], errors='coerce')

# Convertir montos a número
df_facturas['total'] = pd.to_numeric(df_facturas['total'], errors='coerce')
df_facturas['abono'] = pd.to_numeric(df_facturas['abono'], errors='coerce').fillna(0)

# Crear columnas nuevas derivadas de la fecha
# Esto es MUY común en análisis de ventas
df_facturas['año']       = df_facturas['fecha'].dt.year
df_facturas['mes']       = df_facturas['fecha'].dt.month
df_facturas['mes_nombre']= df_facturas['fecha'].dt.strftime('%b')
df_facturas['dia_semana']= df_facturas['fecha'].dt.day_name()
df_facturas['trimestre'] = df_facturas['fecha'].dt.quarter

# Limpiar texto
df_facturas['cliente']  = df_facturas['cliente'].astype(str).str.upper().str.strip()
df_facturas['vendedor'] = df_facturas['vendedor'].astype(str).str.strip()

# Eliminar filas inválidas
antes = len(df_facturas)
df_facturas = df_facturas.dropna(subset=['fecha', 'total'])
df_facturas = df_facturas[df_facturas['total'] > 0]
despues = len(df_facturas)

print(" LIMPIEZA COMPLETADA")
print(f"   Filas antes:   {antes:,}")
print(f"   Filas después: {despues:,}")
print(f"   Eliminadas:    {antes - despues:,} (inválidas)")
print(f"\n Período de datos:")
print(f"   Desde: {df_facturas['fecha'].min().strftime('%d/%m/%Y')}")
print(f"   Hasta: {df_facturas['fecha'].max().strftime('%d/%m/%Y')}")
print(f"\n Vista previa limpia:")
df_facturas.head(3)

 LIMPIEZA COMPLETADA
   Filas antes:   21,928
   Filas después: 17,165
   Eliminadas:    4,763 (inválidas)

 Período de datos:
   Desde: 20/09/2023
   Hasta: 20/09/2025

 Vista previa limpia:

,factura_id,cliente,fecha,tipo,total,vendedor,abono,año,mes,mes_nombre,dia_semana,trimestre
0,40497,JOSE,2025-09-20,Contado,3500.0,Andrew Chamorro,0.0,2025.0,9.0,Sep,Saturday,3.0
1,2310-B,OSCAR,2025-09-20,Contado,1600.0,Alex Chamorro,0.0,2025.0,9.0,Sep,Saturday,3.0
2,2309-B,ROY,2025-09-20,Contado,1200.0,Alex Chamorro,0.0,2025.0,9.0,Sep,Saturday,3.0

In [10]:
# ══════════════════════════════════════════════════
# CELDA 7 — ESTADÍSTICAS DESCRIPTIVAS
# ══════════════════════════════════════════════════
# .describe() es el comando más poderoso para
# entender rápidamente cualquier conjunto de datos.
# Te da 8 estadísticas de golpe.
# ══════════════════════════════════════════════════

print(" ESTADÍSTICAS DESCRIPTIVAS — MONTO DE VENTAS (₡)")
print("=" * 50)

desc = df_facturas['total'].describe()

print(f"\n  count  = {int(desc['count']):>10,}  ← cantidad de transacciones")
print(f"  mean   = ₡{desc['mean']:>10,.0f}  ← ticket PROMEDIO")
print(f"  std    = ₡{desc['std']:>10,.0f}  ← qué tan dispersos son los montos")
print(f"  min    = ₡{desc['min']:>10,.0f}  ← venta más pequeña")
print(f"  25%    = ₡{desc['25%']:>10,.0f}  ← 25% de ventas están BAJO este monto")
print(f"  50%    = ₡{desc['50%']:>10,.0f}  ← venta MEDIANA (el centro real)")
print(f"  75%    = ₡{desc['75%']:>10,.0f}  ← 75% de ventas están BAJO este monto")
print(f"  max    = ₡{desc['max']:>10,.0f}  ← venta más grande registrada")

print("\n" + "=" * 50)
print("  RESUMEN EJECUTIVO")
print("=" * 50)
total_ventas = df_facturas['total'].sum()
dias_total   = (df_facturas['fecha'].max() - df_facturas['fecha'].min()).days

print(f"\n   Ventas TOTALES (2 años):  ₡{total_ventas:>12,.0f}")
print(f"   Promedio MENSUAL:          ₡{total_ventas/(dias_total/30):>12,.0f}")
print(f"   Promedio DIARIO:           ₡{total_ventas/dias_total:>12,.0f}")
print(f"   Total transacciones:        {len(df_facturas):>12,}")

print("\n\n RESUMEN POR AÑO:")
print("-" * 60)
por_año = df_facturas.groupby('año').agg(
    facturas        = ('total', 'count'),
    ventas_total    = ('total', 'sum'),
    ticket_promedio = ('total', 'mean'),
    venta_maxima    = ('total', 'max')
).reset_index()

for _, row in por_año.iterrows():
    print(f"\n   AÑO {int(row['año'])}:")
    print(f"     Facturas emitidas:   {int(row['facturas']):>8,}")
    print(f"     Ventas totales:      ₡{row['ventas_total']:>10,.0f}")
    print(f"     Ticket promedio:     ₡{row['ticket_promedio']:>10,.0f}")
    print(f"     Venta más alta:      ₡{row['venta_maxima']:>10,.0f}")

 ESTADÍSTICAS DESCRIPTIVAS — MONTO DE VENTAS (₡)
==================================================

  count  =     17,165  ← cantidad de transacciones
  mean   = ₡    11,198  ← ticket PROMEDIO
  std    = ₡    22,671  ← qué tan dispersos son los montos
  min    = ₡         2  ← venta más pequeña
  25%    = ₡     2,850  ← 25% de ventas están BAJO este monto
  50%    = ₡     5,400  ← venta MEDIANA (el centro real)
  75%    = ₡    11,000  ← 75% de ventas están BAJO este monto
  max    = ₡ 1,050,947  ← venta más grande registrada

==================================================
  RESUMEN EJECUTIVO
==================================================

   Ventas TOTALES (2 años):  ₡ 192,218,919
   Promedio MENSUAL:          ₡   7,888,601
   Promedio DIARIO:           ₡     262,953
   Total transacciones:              17,165


 RESUMEN POR AÑO:
------------------------------------------------------------

   AÑO 2023:
     Facturas emitidas:      1,986
     Ventas totales:      ₡25,152,096
     Ticket promedio:     ₡    12,665
     Venta más alta:      ₡   474,043

   AÑO 2024:
     Facturas emitidas:      8,479
     Ventas totales:      ₡93,950,753
     Ticket promedio:     ₡    11,080
     Venta más alta:      ₡   665,570

   AÑO 2025:
     Facturas emitidas:      6,700
     Ventas totales:      ₡73,116,070
     Ticket promedio:     ₡    10,913
     Venta más alta:      ₡ 1,050,947

In [11]:
# ══════════════════════════════════════════════════
# CELDA 7B — ¿CUÁLES FUERON LAS VENTAS MÁS ALTAS?
# ══════════════════════════════════════════════════
# .nlargest(n, columna) → trae las N filas más grandes
# .loc[] → filtra filas según una condición

print(" VENTA MÁS ALTA DE CADA AÑO")
print("=" * 60)

for año in [2023, 2024, 2025]:
    # Filtrar solo ese año
    df_año = df_facturas[df_facturas['año'] == año]
    
    # Tomar las 3 ventas más altas de ese año
    top3 = df_año.nlargest(3, 'total')[['factura_id','fecha','cliente','vendedor','total','tipo']]
    
    print(f"\n   AÑO {año} — Top 3 ventas más altas:")
    print(f"  {'-'*55}")
    for i, (_, row) in enumerate(top3.iterrows(), 1):
        print(f"  {i}. Factura:  {row['factura_id']}")
        print(f"     Fecha:     {row['fecha'].strftime('%d/%m/%Y')}")
        print(f"     Cliente:   {row['cliente']}")
        print(f"     Vendedor:  {row['vendedor']}")
        print(f"     Monto:     ₡{row['total']:,.0f}")
        print(f"     Tipo:      {row['tipo']}")
        print()

 VENTA MÁS ALTA DE CADA AÑO
============================================================

   AÑO 2023 — Top 3 ventas más altas:
  -------------------------------------------------------
  1. Factura:  22345
     Fecha:     15/11/2023
     Cliente:   DAGOBERTO MEJIAS GOMEZ LO DE RAQUEL
     Vendedor:  Andrew Chamorro
     Monto:     ₡474,043
     Tipo:      Contado

  2. Factura:  22498
     Fecha:     22/11/2023
     Cliente:   ASOCIACION DE DESARROLLO INTEGRAL DE FINCA SAN JOSE Y CHIRRIPO DE RIO FRIO HORQU
     Vendedor:  Jenny Trejos Perez
     Monto:     ₡319,688
     Tipo:      Contado

  3. Factura:  22306
     Fecha:     14/11/2023
     Cliente:   JOSE ANGEL FLORES VALVERDE
     Vendedor:  Charlie Marenco Chamorro
     Monto:     ₡316,620
     Tipo:      Contado


   AÑO 2024 — Top 3 ventas más altas:
  -------------------------------------------------------
  1. Factura:  26672
     Fecha:     19/04/2024
     Cliente:   JOSE DAVID MORALES ARAYA
     Vendedor:  Charlie Marenco Chamorro
     Monto:     ₡665,570
     Tipo:      Contado

  2. Factura:  24346
     Fecha:     30/01/2024
     Cliente:   INVERSIONES CONSTRUCTIVAS ANGRAVARA SOCIEDAD ANONIMA
     Vendedor:  Jenny Trejos Perez
     Monto:     ₡619,289
     Tipo:      Contado

  3. Factura:  24509
     Fecha:     06/02/2024
     Cliente:   VIVERO RIO FRIO SOCIEDAD ANONIMA
     Vendedor:  Charlie Marenco Chamorro
     Monto:     ₡395,630
     Tipo:      Contado


   AÑO 2025 — Top 3 ventas más altas:
  -------------------------------------------------------
  1. Factura:  747-B
     Fecha:     08/02/2025
     Cliente:   JOHNNY RODRIGO GARCIA LOPEZ
     Vendedor:  Alex Chamorro
     Monto:     ₡1,050,947
     Tipo:      Contado

  2. Factura:  34787
     Fecha:     23/01/2025
     Cliente:   GILBER ASOFEIFA
     Vendedor:  Alex Chamorro
     Monto:     ₡330,000
     Tipo:      Contado

  3. Factura:  1171-B
     Fecha:     27/03/2025
     Cliente:   MANUEL OBANDO
     Vendedor:  Alex Chamorro
     Monto:     ₡308,155
     Tipo:      Contado

In [15]:
# CELDA 8 — ANÁLISIS POR VENDEDOR

por_vendedor = df_facturas.groupby('vendedor').agg(
    facturas        = ('total', 'count'),
    ventas_total    = ('total', 'sum'),
    ticket_promedio = ('total', 'mean'),
    venta_maxima    = ('total', 'max'),
    venta_minima    = ('total', 'min'),
).reset_index()

total_general = por_vendedor['ventas_total'].sum()
por_vendedor['participacion_%'] = (por_vendedor['ventas_total'] / total_general * 100).round(1)
por_vendedor = por_vendedor.sort_values('ventas_total', ascending=False).reset_index(drop=True)

print(" ANÁLISIS COMPLETO POR VENDEDOR")
print("=" * 65)
print(f"\n{'#':<3} {'Vendedor':<25} {'Facturas':>8} {'Ventas Total':>14} {'Participación':>14}")
print("-" * 70)

for i, row in por_vendedor.iterrows():
    barra = '█' * int(row['participacion_%'] / 2)
    print(f"{i+1:<3} {row['vendedor']:<25} {int(row['facturas']):>8,} "
          f"₡{row['ventas_total']:>12,.0f} {row['participacion_%']:>12.1f}%  {barra}")
    print(f"    {'':25} Ticket prom: ₡{row['ticket_promedio']:>10,.0f}   "
          f"Máx: ₡{row['venta_maxima']:>8,.0f}")
    print()

 ANÁLISIS COMPLETO POR VENDEDOR
=================================================================

#   Vendedor                  Facturas   Ventas Total  Participación
----------------------------------------------------------------------
1   Charlie Marenco Chamorro     6,914 ₡  86,563,457         45.0%  ██████████████████████
                              Ticket prom: ₡    12,520   Máx: ₡ 665,570

2   Alex Chamorro                4,806 ₡  62,398,545         32.5%  ████████████████
                              Ticket prom: ₡    12,983   Máx: ₡1,050,947

3   Vladimir Hernandez Trejos    2,845 ₡  17,673,712          9.2%  ████
                              Ticket prom: ₡     6,212   Máx: ₡  83,700

4   Jenny Trejos Perez             969 ₡  10,627,685          5.5%  ██
                              Ticket prom: ₡    10,968   Máx: ₡ 619,289

5   nan                            422 ₡   5,788,044          3.0%  █
                              Ticket prom: ₡    13,716   Máx: ₡ 179,350

6   Andrew Chamorro                632 ₡   5,449,266          2.8%  █
                              Ticket prom: ₡     8,622   Máx: ₡ 474,043

7   LUIS MARENCO CHAMORRO          261 ₡   1,549,590          0.8%
                              Ticket prom: ₡     5,937   Máx: ₡  54,904

8   Anderson Rojas Gonzales        178 ₡   1,173,195          0.6%
                              Ticket prom: ₡     6,591   Máx: ₡  29,000

9   Tamara Chinchilla              122 ₡     914,352          0.5%
                              Ticket prom: ₡     7,495   Máx: ₡  80,000

10  Pablo Miguel Rojas Chamorro       16 ₡      81,073          0.0%
                              Ticket prom: ₡     5,067   Máx: ₡  24,195

In [16]:
# CELDA 9 — EVOLUCIÓN DE VENDEDORES POR AÑO

print(" VENTAS POR VENDEDOR — AÑO A AÑO")
print("=" * 65)

df_vendedores = df_facturas[~df_facturas['vendedor'].isin(['SIN ASIGNAR', 'nan'])]

pivot = df_vendedores.pivot_table(
    index    = 'vendedor',
    columns  = 'año',
    values   = 'total',
    aggfunc  = 'sum',
    fill_value = 0
).round(0)

pivot['TOTAL'] = pivot.sum(axis=1)
pivot = pivot.sort_values('TOTAL', ascending=False)

print(f"\n  {'Vendedor':<25}", end='')
for col in pivot.columns:
    print(f"  {str(col):>14}", end='')
print()
print("  " + "-" * 75)

for vendedor, row in pivot.iterrows():
    print(f"  {vendedor:<25}", end='')
    for val in row:
        print(f"  ₡{val:>12,.0f}", end='')
    print()

print(f"\n\n CRECIMIENTO POR VENDEDOR (2024 → 2025):")
print("-" * 50)
for vendedor, row in pivot.iterrows():
    v2024 = row.get(2024, 0)
    v2025 = row.get(2025, 0)
    if v2024 > 0:
        crecimiento = ((v2025 - v2024) / v2024) * 100
        emoji = "" if crecimiento >= 0 else "📉"
        print(f"  {emoji} {vendedor:<28} {crecimiento:>+.1f}%")

 VENTAS POR VENDEDOR — AÑO A AÑO
=================================================================

  Vendedor                           2023.0          2024.0          2025.0           TOTAL
  ---------------------------------------------------------------------------
  Charlie Marenco Chamorro   ₡  10,446,665  ₡  47,583,011  ₡  28,533,781  ₡  86,563,457
  Alex Chamorro              ₡  10,016,143  ₡  28,414,705  ₡  23,967,697  ₡  62,398,545
  Vladimir Hernandez Trejos  ₡   1,741,555  ₡   8,454,561  ₡   7,477,596  ₡  17,673,712
  Jenny Trejos Perez         ₡   1,576,708  ₡   5,172,896  ₡   3,878,081  ₡  10,627,685
  Andrew Chamorro            ₡   1,263,227  ₡   1,656,302  ₡   2,529,737  ₡   5,449,266
  LUIS MARENCO CHAMORRO      ₡           0  ₡           0  ₡   1,549,590  ₡   1,549,590
  Anderson Rojas Gonzales    ₡           0  ₡           0  ₡   1,173,195  ₡   1,173,195
  Tamara Chinchilla          ₡           0  ₡     910,652  ₡       3,700  ₡     914,352
  Pablo Miguel Rojas Chamorro  ₡           0  ₡           0  ₡      81,073  ₡      81,073


 CRECIMIENTO POR VENDEDOR (2024 → 2025):
--------------------------------------------------

In [17]:
# ════════════════════════════════════════════════— ¿POR QUÉ CAYERON LAS VENTAS EN 2025?
# Investigación mes a mes
# ══════════════════════════════════════════════════

print(" INVESTIGANDO LA CAÍDA DE VENTAS 2024 → 2025")
print("=" * 60)

# DATO BASE
v2024 = df_facturas[df_facturas['año'] == 2024]['total'].sum()
v2025 = df_facturas[df_facturas['año'] == 2025]['total'].sum()
diferencia = v2025 - v2024
caida_pct  = (diferencia / v2024) * 100

print(f"\n  Ventas 2024:     ₡{v2024:>12,.0f}")
print(f"  Ventas 2025:     ₡{v2025:>12,.0f}")
print(f"  Diferencia:      ₡{diferencia:>12,.0f}")
print(f"  Variación:        {caida_pct:>+.1f}%")

# ── PISTA 1 — ¿Cuántos meses tenemos de cada año? ──
print(f"\n\n PISTA 1 — ¿Cuántos meses de datos hay por año?")
print("-" * 50)
meses_por_año = df_facturas.groupby('año')['mes'].nunique()
facturas_por_año = df_facturas.groupby('año')['total'].count()

for año in [2023, 2024, 2025]:
    meses = meses_por_año.get(año, 0)
    facts = facturas_por_año.get(año, 0)
    print(f"  {año}: {meses} meses de datos  →  {facts:,} facturas")

# ── PISTA 2 — Ventas MES A MES comparando 2024 vs 2025 ──
print(f"\n\n PISTA 2 — VENTAS MES A MES (2024 vs 2025)")
print("-" * 60)

meses_nombre = {1:'Enero',2:'Febrero',3:'Marzo',4:'Abril',
                5:'Mayo',6:'Junio',7:'Julio',8:'Agosto',
                9:'Septiembre',10:'Octubre',11:'Noviembre',12:'Diciembre'}

ventas_mes = df_facturas.groupby(['año','mes'])['total'].sum().reset_index()

print(f"\n  {'Mes':<12} {'2024':>14} {'2025':>14} {'Diferencia':>14} {'Var%':>8}")
print(f"  {'-'*58}")

for mes in range(1, 13):
    v_2024 = ventas_mes[(ventas_mes['año']==2024) & (ventas_mes['mes']==mes)]['total'].sum()
    v_2025 = ventas_mes[(ventas_mes['año']==2025) & (ventas_mes['mes']==mes)]['total'].sum()
    
    if v_2024 == 0 and v_2025 == 0:
        continue
        
    diff = v_2025 - v_2024
    if v_2024 > 0:
        var = (diff / v_2024) * 100
        emoji = "" if var >= 0 else ""
        print(f"  {meses_nombre[mes]:<12} ₡{v_2024:>12,.0f} ₡{v_2025:>12,.0f} "
              f"₡{diff:>12,.0f} {var:>+7.1f}% {emoji}")
    else:
        print(f"  {meses_nombre[mes]:<12} {'(sin datos)':>14} ₡{v_2025:>12,.0f} {'---':>14}")

 INVESTIGANDO LA CAÍDA DE VENTAS 2024 → 2025
============================================================

  Ventas 2024:     ₡  93,950,753
  Ventas 2025:     ₡  73,116,070
  Diferencia:      ₡ -20,834,683
  Variación:        -22.2%


 PISTA 1 — ¿Cuántos meses de datos hay por año?
--------------------------------------------------
  2023: 4 meses de datos  →  1,986 facturas
  2024: 12 meses de datos  →  8,479 facturas
  2025: 9 meses de datos  →  6,700 facturas


 PISTA 2 — VENTAS MES A MES (2024 vs 2025)
------------------------------------------------------------

  Mes                    2024           2025     Diferencia     Var%
  ----------------------------------------------------------
  Enero        ₡   7,410,372 ₡   9,828,130 ₡   2,417,758   +32.6%
  Febrero      ₡   6,527,940 ₡   9,889,646 ₡   3,361,706   +51.5%
  Marzo        ₡   8,550,041 ₡   7,316,790 ₡  -1,233,251   -14.4%
  Abril        ₡   7,579,428 ₡   8,545,993 ₡     966,565   +12.8%
  Mayo         ₡   8,609,028 ₡   7,403,975 ₡  -1,205,052   -14.0%
  Junio        ₡   8,070,671 ₡   7,939,901 ₡    -130,770    -1.6%
  Julio        ₡   9,050,392 ₡   7,660,024 ₡  -1,390,369   -15.4%
  Agosto       ₡   7,237,882 ₡   7,968,386 ₡     730,503   +10.1%
  Septiembre   ₡   7,239,518 ₡   6,563,224 ₡    -676,294    -9.3%
  Octubre      ₡   7,137,061 ₡           0 ₡  -7,137,061  -100.0%
  Noviembre    ₡   7,686,408 ₡           0 ₡  -7,686,408  -100.0%
  Diciembre    ₡   8,852,010 ₡           0 ₡  -8,852,010  -100.0%

In [18]:
# ═════════════════════════════════════════════ — ¿FUE MENOS CLIENTES O MENOS GASTO?
# Hay DOS razones por las que pueden caer las ventas:
# 1. Vinieron MENOS clientes (menos facturas)
# 2. Cada cliente gastó MENOS (ticket más bajo)
# ══════════════════════════════════════════════════

print(" PISTA 3 — ¿MENOS CLIENTES O MENOS GASTO POR CLIENTE?")
print("=" * 60)

resumen = df_facturas.groupby('año').agg(
    facturas        = ('total', 'count'),
    ventas_total    = ('total', 'sum'),
    ticket_promedio = ('total', 'mean'),
    clientes_unicos = ('cliente', 'nunique')
).reset_index()

for _, row in resumen.iterrows():
    print(f"\n   AÑO {int(row['año'])}:")
    print(f"     Facturas emitidas:    {int(row['facturas']):>8,}")
    print(f"     Clientes únicos:      {int(row['clientes_unicos']):>8,}")
    print(f"     Ventas totales:       ₡{row['ventas_total']:>10,.0f}")
    print(f"     Ticket promedio:      ₡{row['ticket_promedio']:>10,.0f}")

# Comparar 2024 vs 2025
f2024 = resumen[resumen['año']==2024]['facturas'].values[0]
f2025 = resumen[resumen['año']==2025]['facturas'].values[0]
t2024 = resumen[resumen['año']==2024]['ticket_promedio'].values[0]
t2025 = resumen[resumen['año']==2025]['ticket_promedio'].values[0]
c2024 = resumen[resumen['año']==2024]['clientes_unicos'].values[0]
c2025 = resumen[resumen['año']==2025]['clientes_unicos'].values[0]

print(f"\n\n   COMPARACIÓN DIRECTA 2024 → 2025:")
print(f"  {'':30} {'2024':>10} {'2025':>10} {'Cambio':>10}")
print(f"  {'-'*60}")
print(f"  {'Facturas emitidas':<30} {int(f2024):>10,} {int(f2025):>10,} "
      f"{((f2025-f2024)/f2024*100):>+9.1f}%")
print(f"  {'Clientes únicos':<30} {int(c2024):>10,} {int(c2025):>10,} "
      f"{((c2025-c2024)/c2024*100):>+9.1f}%")
print(f"  {'Ticket promedio':<30} ₡{t2024:>9,.0f} ₡{t2025:>9,.0f} "
      f"{((t2025-t2024)/t2024*100):>+9.1f}%")

print(f"\n\n   DIAGNÓSTICO:")
if f2025 < f2024 and t2025 < t2024:
    print("   DOBLE PROBLEMA: Menos clientes Y menor gasto por cliente")
elif f2025 < f2024:
    print("    El problema es VOLUMEN: vinieron menos clientes")
elif t2025 < t2024:
    print("    El problema es TICKET: los clientes gastaron menos")

 PISTA 3 — ¿MENOS CLIENTES O MENOS GASTO POR CLIENTE?
============================================================

   AÑO 2023:
     Facturas emitidas:       1,986
     Clientes únicos:         1,004
     Ventas totales:       ₡25,152,096
     Ticket promedio:      ₡    12,665

   AÑO 2024:
     Facturas emitidas:       8,479
     Clientes únicos:         3,077
     Ventas totales:       ₡93,950,753
     Ticket promedio:      ₡    11,080

   AÑO 2025:
     Facturas emitidas:       6,700
     Clientes únicos:         2,487
     Ventas totales:       ₡73,116,070
     Ticket promedio:      ₡    10,913


   COMPARACIÓN DIRECTA 2024 → 2025:
                                       2024       2025     Cambio
  ------------------------------------------------------------
  Facturas emitidas                   8,479      6,700     -21.0%
  Clientes únicos                     3,077      2,487     -19.2%
  Ticket promedio                ₡   11,080 ₡   10,913      -1.5%


   DIAGNÓSTICO:
   DOBLE PROBLEMA: Menos clientes Y menor gasto por cliente

In [19]:
# ══════════════════════════════════════════════════— IDENTIFICAR EL MES EXACTO DE LA CAÍDA
# ══════════════════════════════════════════════════

print(" PISTA 4 — ¿EN QUÉ MES EMPEZÓ LA CAÍDA?")
print("=" * 55)

ventas_mensual = df_facturas.groupby(['año','mes']).agg(
    total    = ('total', 'sum'),
    facturas = ('total', 'count')
).reset_index()
ventas_mensual['periodo'] = ventas_mensual.apply(
    lambda r: f"{meses_nombre[int(r['mes'])][:3]} {int(r['año'])}", axis=1)

# Ordenar cronológicamente
ventas_mensual = ventas_mensual.sort_values(['año','mes'])

# Calcular crecimiento mes a mes
ventas_mensual['var_mes_%'] = ventas_mensual['total'].pct_change() * 100

print(f"\n  {'Período':<12} {'Ventas':>14} {'Facturas':>10} {'Var vs mes anterior':>20}")
print(f"  {'-'*60}")
for _, row in ventas_mensual.iterrows():
    var_str = f"{row['var_mes_%']:>+.1f}%" if not pd.isna(row['var_mes_%']) else "  base"
    emoji = "" if row.get('var_mes_%', 0) >= 0 else ""
    separador = "  ──────" if row['mes'] == 1 else ""
    print(f"  {row['periodo']:<12} ₡{row['total']:>12,.0f} {int(row['facturas']):>10,}"
          f"  {var_str:>10} {emoji} {separador}")

 PISTA 4 — ¿EN QUÉ MES EMPEZÓ LA CAÍDA?
=======================================================

  Período              Ventas   Facturas  Var vs mes anterior
  ------------------------------------------------------------
  Sep 2023     ₡   2,952,793        220        base
  Oct 2023     ₡   7,896,362        584     +167.4%
  Nov 2023     ₡   6,702,330        529      -15.1%
  Dic 2023     ₡   7,600,610        653      +13.4%
  Ene 2024     ₡   7,410,372        647       -2.5%    ──────
  Feb 2024     ₡   6,527,940        591      -11.9%
  Mar 2024     ₡   8,550,041        734      +31.0%
  Abr 2024     ₡   7,579,428        664      -11.4%
  May 2024     ₡   8,609,028        737      +13.6%
  Jun 2024     ₡   8,070,671        649       -6.3%
  Jul 2024     ₡   9,050,392        750      +12.1%
  Ago 2024     ₡   7,237,882        787      -20.0%
  Sep 2024     ₡   7,239,518        742       +0.0%
  Oct 2024     ₡   7,137,061        677       -1.4%
  Nov 2024     ₡   7,686,408        697       +7.7%
  Dic 2024     ₡   8,852,010        804      +15.2%
  Ene 2025     ₡   9,828,130        877      +11.0%    ──────
  Feb 2025     ₡   9,889,646        737       +0.6%
  Mar 2025     ₡   7,316,790        695      -26.0%
  Abr 2025     ₡   8,545,993        709      +16.8%
  May 2025     ₡   7,403,975        757      -13.4%
  Jun 2025     ₡   7,939,901        710       +7.2%
  Jul 2025     ₡   7,660,024        780       -3.5%
  Ago 2025     ₡   7,968,386        787       +4.0%
  Sep 2025     ₡   6,563,224        648      -17.6%

##  Estrategia para generar ventas desde el Día 1
### Basada 100% en datos reales del análisis

---

###  Punto de Equilibrio Mensual — La Victoria

| Categoría | Concepto | Monto (₡) |
|---|---|---|
| Operativo | Alquiler + Luz + Agua + Internet + Basura | ₡273,000 |
| Servicios | Sistema + Contabilidad + IA + Teléfono | ₡69,600 |
| Seguros | Rosa + Charlie + Póliza | ₡105,000 |
| Salarios | Rosa + Charlie (₡100,000/semana c/u) | ₡800,000 |
| | **TOTAL GASTOS FIJOS** | **₡1,247,600** |

#### Cálculo del mínimo para sobrevivir:Margen promedio estimado: 35%
₡1,247,600 ÷ 35% = ₡3,564,571 en ventas mínimas/mes
= 322 facturas al mes
= 11 facturas/día (abriendo 30 días)
= 14 facturas/día (abriendo 23 días hábiles)

>  El negocio anterior hacía **30+ facturas diarias** en sus mejores meses.  
> El punto de equilibrio es **totalmente alcanzable**.

---

###  Estrategia 1 — Inventario inicial inteligente

De los **10,120 artículos** del catálogo, no se necesitan todos.  
Se necesitan los **correctos**. Prioridad día 1:

| Prioridad | Categoría | Razón |
|---|---|---|
|  1 | Filtros (aceite, aire, combustible) | Mayor volumen de artículos y alta rotación |
|  2 | Pastillas y zapatas de freno | Demanda constante, urgente |
|  3 | Eléctrico (relays, fusibles, carbones) | Tickets más altos |
| 4 | Hules y bushings | Alta frecuencia de compra |
| 5 | Roles y rodamientos | Críticos, el cliente no puede esperar |

---

###  Estrategia 2 — El momento ideal para abrir

Los datos confirman que **Enero y Febrero son los mejores meses**:

| Mes | Ventas | Observación |
|---|---|---|
| Febrero 2025 | ₡9,889,646 |  Récord absoluto histórico |
| Enero 2025 | ₡9,828,130 |  Segundo mejor mes |
| Julio 2024 | ₡9,050,392 | Tercer mejor mes |

>  **¿Por qué enero/febrero?**  
> La gente hace mantenimiento preventivo después de las fiestas.  
> Abrir en Q1 significa **arrancar con viento a favor**.
>Julio estan las pre tiempo de fechas de vacaciones de medio año, cuando las personas sale de viaje
---

###  Estrategia 3 — Capturar clientes desde el inicio

El negocio anterior tenía **3,077 clientes únicos en 2024**.  
Esos clientes ya compraban repuestos en la zona.

**Plan de captura:**
- WhatsApp activo desde el **día 1** con catálogo y precios
- Precio competitivo en **filtros y aceites** (productos gancho)
- Disponibilidad inmediata en **frenos y embragues** (no pueden esperar)
- Base de datos de clientes desde la **primera venta**

---

###  Metas realistas — Mes 1

| Meta | Facturas/día | Ventas mensuales |
|---|---|---|
| 🔴 Mínima (sobrevivir) | 14 | ₡3,600,000 |
| 🟡 Cómoda | 20 | ₡5,000,000 |
| 🟢 Ambiciosa | 28 | ₡7,000,000 |

>  **Referencia clave:** El negocio de referencia  
> **nunca bajó de ₡6.5M mensual** en ningún mes completo de 2024.  
> La Victoria tiene una base sólida para planificar sobre eso.

---

###  Lecciones aprendidas del negocio de referencia

| Problema detectado | Solución para La Victoria |
|---|---|
| 45% de ventas dependían de Charlie M. | Rosa debe ser la vendedora principal del mostrador |
| 4% de facturas sin vendedor asignado | Registrar **siempre** quién realizó cada venta |
| Sin detalle de productos por factura | El sistema debe registrar cada artículo vendido |
| 880 facturas sin vendedor (nan) | Campo vendedor **obligatorio** en el sistema |

---
*Fuente: Análisis de datos reales Sep 2023 → Sep 2025*  
*Gastos fijos: Archivo Gastos_Fijos_La_Victoria.xlsx*

In [25]:
# ═════════════════════════ — ANÁLISIS DEL CATÁLOGO DE ARTÍCULOS
# Este es el análisis más valioso para definir
# qué debe tener La Victoria en inventario.
# ══════════════════════════════════════════════════

print("ANÁLISIS DEL CATÁLOGO DE ARTÍCULOS")
print("=" * 60)

# Estado general del catálogo
total_articulos  = len(df_articulos)
activos          = len(df_articulos[df_articulos['Estado'] == 'Activo'])
con_stock        = len(df_articulos[df_articulos['Inventario'] > 0])
sin_stock        = len(df_articulos[df_articulos['Inventario'] <= 0])
valor_inventario = (df_articulos['Inventario'] * df_articulos['Costo neto']).sum()

print(f"\nRESUMEN GENERAL DEL CATÁLOGO:")
print(f"  Total artículos registrados:    {total_articulos:>8,}")
print(f"  Artículos activos:              {activos:>8,}")
print(f"  Artículos con stock físico:     {con_stock:>8,}")
print(f"  Artículos sin stock:            {sin_stock:>8,}")
print(f"  Valor total en inventario:      {valor_inventario:>12,.0f}")

# Porcentaje de artículos sin stock
pct_sin_stock = sin_stock / total_articulos * 100
print(f"\n  Porcentaje sin stock:           {pct_sin_stock:>7.1f}%")
print(f"  Porcentaje con stock:           {100-pct_sin_stock:>7.1f}%")

ANÁLISIS DEL CATÁLOGO DE ARTÍCULOS
============================================================

RESUMEN GENERAL DEL CATÁLOGO:
  Total artículos registrados:      10,120
  Artículos activos:                10,094
  Artículos con stock físico:        3,183
  Artículos sin stock:               6,937
  Valor total en inventario:        20,807,162

  Porcentaje sin stock:              68.5%
  Porcentaje con stock:              31.5%

In [36]:
# ════════════════════════════════ — ANÁLISIS POR CATEGORIA
# Identificar cuáles categorías tienen más
# artículos, mejor margen y mayor valor
# ══════════════════════════════════════════════════

print("ANÁLISIS POR CATEGORIA DE PRODUCTO")
print("=" * 75)

# Agrupar por Línea (categoría del artículo)
por_categoria = df_articulos.groupby('Línea').agg(
    total_articulos  = ('Código', 'count'),
    con_stock        = ('Inventario', lambda x: (x > 0).sum()),
    unidades_stock   = ('Inventario', 'sum'),
    precio_promedio  = ('Precio venta', 'mean'),
    costo_promedio   = ('Costo neto', 'mean'),
    margen_promedio  = ('%Utilidad', 'mean'),
).reset_index()

# Calcular valor del inventario por categoría
por_categoria['valor_inventario'] = (
    por_categoria['unidades_stock'] * por_categoria['costo_promedio']
)

# Calcular porcentaje de artículos con stock
por_categoria['pct_con_stock'] = (
    por_categoria['con_stock'] / por_categoria['total_articulos'] * 100
).round(1)

# Ordenar por total de artículos
por_categoria = por_categoria[
    por_categoria['total_articulos'] >= 5
].sort_values('total_articulos', ascending=False).reset_index(drop=True)

print(f"\n{'#':<3} {'Categoria':<35} {'Articulos':>9} {'Con Stock':>9} {'Margen%':>8} {'Valor Inv':>14}")
print("-" * 82)

for i, row in por_categoria.iterrows():
    categoria = str(row['Línea'])[:33]
    print(f"{i+1:<3} {categoria:<35} "
          f"{int(row['total_articulos']):>9,} "
          f"{int(row['con_stock']):>9,} "
          f"{row['margen_promedio']:>7.1f}% "
          f"  {row['valor_inventario']:>12,.0f}")

ANÁLISIS POR CATEGORIA DE PRODUCTO
===========================================================================

#   Categoria                           Articulos Con Stock  Margen%      Valor Inv
----------------------------------------------------------------------------------
1   PARTES DE CARROSERIA                      895       132    82.7%     24,010,147
2   BEARING                                   620        85    90.1%     29,045,638
3   DEPARTAMENTO DE ELECTRO                   514       164    83.4%     19,640,523
4   TUERCAS Y TORNILLOS                       367       289   112.6%      9,378,262
5   ACCESORIOS                                332       114    70.5%     10,836,084
6   FAJAS DE ABANICO                          312       109    81.2%        827,020
7   PASTILLAS DE FRENO                        276        84    84.4%        869,594
8   BUSCHIN DE TIJERETA /RESORTE,TENS         269       182    86.8%      1,803,361
9   ADICTIVOS GENERAL                         259       101    50.7%        722,455
10  MOTOR                                     249        28    86.7%      5,833,341
11  SOPORTES DE MOTOR Y CAJAS ,TRANFE         238        62    68.8%        634,914
12  AMORTIGUADORES                            223        19    48.3%        496,042
13  BUJIAS. BOBINAS YCABLES                   213        46    89.8%      1,413,093
14  ROL DE CONO Y COPA Y BOCINAS              195        72    71.2%      1,516,681
15  SENSORES ELECTRICOS                       180        17    68.0%        295,547
16  MANGUERA COMBUSTIBLE/FRENO/RADIAD         172        41    97.2%        406,006
17  ROTULAS DIRECION                          172        77    94.1%        873,642
18  FARROL DIRECIONAL                         168        47   123.5%        815,810
19  RETENEDORES ESPECIALES                    159        42   136.6%        187,296
20  ROTULAS SUSPENCION                        145        54   115.4%      1,004,684
21  FERRETERIA                                138        78    53.7%      3,762,073
22  RETENEDORES NJ100-NJ200                   134        68    85.5%        276,565
23  FAROLERIA                                 132        13    46.7%       -105,117
24  FILTROS AIRE                              131        78    63.6%        502,102
25  FILTROS COMBUSTIBLE                       120        57    85.1%        631,507
26  ZAPATAS DE FRENO                          119        28    75.7%        317,193
27  ROTULAS ESTABILISADORAS                   118        37    83.9%        432,007
28  EMPAQUE TAPA VALVULA                      111        44   116.6%        185,875
29  EMPAQUES DE CABEZOTES                     111        18    90.6%        135,113
30  FILTROS P/ ACEITE                         111        63    63.7%        557,865
31  LUBRICANTES Y GRASAS                      109        15    38.4%        565,726
32  CABLES VELOCIMETROS/FRENO/MARCHA/         104        16    80.0%         64,953
33  ROTULAS CREMALLERA                        102        54   110.7%        802,426
34  REGULADORES,PLACAS, CARBONES Y MA          96        32    93.0%        335,318
35  FLOSSER                                    92        70    62.6%      2,793,112
36  FAJAS DISTRIBUCION                         92        18    88.1%        193,333
37  HULES DE ESTABILISADORA                    89        70   140.6%        317,864
38  GALLETAS DE COMPENSADOR                    85        30    64.9%        462,070
39  BOMBA AXULIAR DE FRENO                     84        11    78.7%         73,793
40  KIT BPF/BPC/BAF/BAC/                       83        21    84.2%        159,669
41  HERRAMIENTAS                               80        25    43.2%        412,266
42  ROL DE LA SERIE BALIN                      78        47    71.8%      1,297,584
43  DISCO DE CLUTCH                            77         1    41.9%         40,367
44  ANILLOS                                    75        22    70.2%        305,080
45  LUBRICANTES CHARLY                         75        12    48.5%      2,343,231
46  BOTAS DE EJE Y CREMAYERA                   72        21    69.6%        248,315
47  BOMBA DE AGUA                              71        13   102.5%        446,474
48  ESCOBILLAS                                 65        19    65.0%        143,259
49  ASESORIOS PARA FRENO                       65        36   112.2%        256,467
50  ROL TENSOR                                 65         8    80.6%         85,892
51  PUNTAS DE EJE                              63        14    65.1%        315,535
52  EMPAQUES DE ADMISION, ESCAPE Y MU          61        14   102.1%        412,332
53  PLATO DE PRESION                           57         2    46.7%         72,874
54  BOMBAS PRINCIPAL DE FRENO                  53        11    67.5%        319,799
55  TIJERETA                                   52         3    62.4%         70,122
56  ROL DE EMPUJE                              51         8    72.3%         92,998
57  PINTURA SPRAY                              44        15    47.0%         44,662
58  LLANTAS Y NEUMATICOS Y PARCHES             44        13    40.1%      1,824,378
59  TAPA DE DISTIBUIDOR                        43        18    71.6%        105,142
60  BOMBA AUX DE CLUTCH                        43        10    68.7%        114,175
61  BRAZOS LOCO Y PITMA,BARRA CENTRAL          37         6    73.9%        105,951
62  SILENCIADORES Y MAS                        36         3    65.2%         26,337
63  ROTOR DE DISTRIBUIDOR                      36        16    96.9%         77,035
64  NEUMATICOS Y INICIVOS                      35        25    50.5%        799,894
65  BOMBAS PRINCIPAL DE CLUCHT                 33         2    58.9%         29,745
66  SOPORTE DE BARRA                           31        14    57.7%        166,453
67  BOMBA DE GASOLINA                          31        13    64.1%        217,051
68  FILTRO AIRE A/C                            30        18    72.5%        103,147
69  BOCINAS                                    30         8    66.1%        151,437
70  REP MOTO R-CHAMORRO                        29         4    44.7%         85,182
71  RETENEDORES NJ000-100                      27        15   123.2%         57,140
72  UNIONES DE BARRA                           27        14    68.9%        139,191
73  RETENEDORES NK                             26        15    94.5%         70,104
74  HULES DE CAJAS DE CREMALLERA               23        14   117.8%         28,654
75  RETENEDORES NJ200-NJ300                    22         8   104.8%         38,599
76  ROL DE GUÍA                                22         2    66.0%         24,661
77  HULES DE TENSORA                           22        16   114.3%        118,293
78  RETENEDORES NJ300-NJ400                    22        19    97.8%         70,245
79  PORTA CARBONERAS                           22         3    61.6%         18,378
80  BATERIAS                                   16         0    31.3%        -45,342
81  RETENEDORES NJ500-NJ600                    16        13    91.1%         41,986
82  MANILLAS                                   16         4 11351.0%         26,608
83  HULES DE BALANCIN                          15        12    78.0%         76,523
84  NAN                                        14         0     0.0%              0
85  RETENEDORES NJ400-NJ500                    14        13    77.3%         38,216
86  DISCOS Y TAMBOR                            13         1    45.0%         31,659
87  CONSIGNACION DE MOLINA                     12         1    35.8%         -4,022
88  REPUESTOS P/MOTO                           12         1    47.2%          4,092
89  POLEAS DE ABANICO                          12         2    79.6%         27,794
90  CABLES AUTOMOTRIZ                          11         3    63.0%         20,446
91  HULES MUFLA,Y HULES MAS                     8         6   135.8%        116,696
92  KIT DE BOMBA PRINCIPAL DE FRENO             7         1    38.4%         12,236
93  ROLL EMPUJE                                 7         1    69.1%         13,001
94  REP MOTO                                    7         1    47.1%          2,671
95  EXPRES Y MAS                                6         4 31448.7%        249,583
96  ROL DE DISTRIBUCIÓN                         6         0    45.3%              0

In [30]:
# ══════════════════════— RENTABILIDAD POR CATEGORIA
# Identificar cuáles categorías dejan más ganancia
# ══════════════════════════════════════════════════

print("RENTABILIDAD POR CATEGORIA — ORDENADO POR MARGEN")
print("=" * 65)

# Filtrar categorías con margen válido y suficientes artículos
rentabilidad = por_categoria[
    (por_categoria['margen_promedio'] > 0) &
    (por_categoria['total_articulos'] >= 5)
].sort_values('margen_promedio', ascending=False).reset_index(drop=True)

print(f"\n{'#':<3} {'Categoria':<35} {'Margen%':>8} {'Precio Prom':>12} {'Costo Prom':>12}")
print("-" * 75)

for i, row in rentabilidad.iterrows():
    categoria = str(row['Línea'])[:33]
    # Clasificar el margen
    if row['margen_promedio'] >= 60:
        nivel = "ALTO"
    elif row['margen_promedio'] >= 35:
        nivel = "MEDIO"
    else:
        nivel = "BAJO"

    print(f"{i+1:<3} {categoria:<35} "
          f"{row['margen_promedio']:>7.1f}%  "
          f"  {row['precio_promedio']:>10,.0f}  "
          f"  {row['costo_promedio']:>10,.0f}  "
          f"  [{nivel}]")

# Resumen de márgenes
print(f"\nRESUMEN DE MARGENES:")
print(f"  Categorias con margen ALTO  (>=60%): "
      f"{len(rentabilidad[rentabilidad['margen_promedio'] >= 60]):>3}")
print(f"  Categorias con margen MEDIO (35-60%): "
      f"{len(rentabilidad[(rentabilidad['margen_promedio'] >= 35) & (rentabilidad['margen_promedio'] < 60)]):>3}")
print(f"  Categorias con margen BAJO  (<35%):  "
      f"{len(rentabilidad[rentabilidad['margen_promedio'] < 35]):>3}")

RENTABILIDAD POR CATEGORIA — ORDENADO POR MARGEN
=================================================================

#   Categoria                            Margen%  Precio Prom   Costo Prom
---------------------------------------------------------------------------
1   EXPRES Y MAS                        31448.7%        41,584           524    [ALTO]
2   MANILLAS                            11351.0%         9,747         5,322    [ALTO]
3   HULES DE ESTABILISADORA               140.6%         2,420         1,078    [ALTO]
4   RETENEDORES ESPECIALES                136.6%         8,726         4,072    [ALTO]
5   HULES MUFLA,Y HULES MAS               135.8%         2,469         1,241    [ALTO]
6   FARROL DIRECIONAL                     123.5%        14,167         6,475    [ALTO]
7   RETENEDORES NJ000-100                 123.2%         4,206         1,843    [ALTO]
8   HULES DE CAJAS DE CREMALLERA          117.8%         3,298         1,433    [ALTO]
9   EMPAQUE TAPA VALVULA                  116.6%         9,022         4,131    [ALTO]
10  ROTULAS SUSPENCION                    115.4%        19,016         9,947    [ALTO]
11  HULES DE TENSORA                      114.3%         3,147         1,577    [ALTO]
12  TUERCAS Y TORNILLOS                   112.6%         1,008           491    [ALTO]
13  ASESORIOS PARA FRENO                  112.2%         6,008         3,178    [ALTO]
14  ROTULAS CREMALLERA                    110.7%        13,577         6,524    [ALTO]
15  RETENEDORES NJ200-NJ300               104.8%         4,059         1,838    [ALTO]
16  BOMBA DE AGUA                         102.5%        33,290        17,859    [ALTO]
17  EMPAQUES DE ADMISION, ESCAPE Y MU     102.1%         3,911         1,740    [ALTO]
18  RETENEDORES NJ300-NJ400                97.8%         3,265         1,495    [ALTO]
19  MANGUERA COMBUSTIBLE/FRENO/RADIAD      97.2%         8,506         4,218    [ALTO]
20  ROTOR DE DISTRIBUIDOR                  96.9%         5,578         2,853    [ALTO]
21  RETENEDORES NK                         94.5%         4,855         2,596    [ALTO]
22  ROTULAS DIRECION                       94.1%        13,935         7,161    [ALTO]
23  REGULADORES,PLACAS, CARBONES Y MA      93.0%        13,435         7,621    [ALTO]
24  RETENEDORES NJ500-NJ600                91.1%         3,374         1,615    [ALTO]
25  EMPAQUES DE CABEZOTES                  90.6%        16,161         8,445    [ALTO]
26  BEARING                                90.1%        34,780        19,573    [ALTO]
27  BUJIAS. BOBINAS YCABLES                89.8%        18,537         9,951    [ALTO]
28  FAJAS DISTRIBUCION                     88.1%        18,000         8,788    [ALTO]
29  BUSCHIN DE TIJERETA /RESORTE,TENS      86.8%         6,728         3,383    [ALTO]
30  MOTOR                                  86.7%        41,139        25,144    [ALTO]
31  RETENEDORES NJ100-NJ200                85.5%         4,636         2,431    [ALTO]
32  FILTROS COMBUSTIBLE                    85.1%        10,869         5,794    [ALTO]
33  PASTILLAS DE FRENO                     84.4%        17,761         9,251    [ALTO]
34  KIT BPF/BPC/BAF/BAC/                   84.2%         9,691         5,151    [ALTO]
35  ROTULAS ESTABILISADORAS                83.9%        11,535         6,172    [ALTO]
36  DEPARTAMENTO DE ELECTRO                83.4%        17,743        10,103    [ALTO]
37  PARTES DE CARROSERIA                   82.7%        29,422        18,210    [ALTO]
38  FAJAS DE ABANICO                       81.2%         8,350         4,285    [ALTO]
39  ROL TENSOR                             80.6%        22,850        12,270    [ALTO]
40  CABLES VELOCIMETROS/FRENO/MARCHA/      80.0%        15,525         8,119    [ALTO]
41  POLEAS DE ABANICO                      79.6%        27,556        13,897    [ALTO]
42  BOMBA AXULIAR DE FRENO                 78.7%        14,224         7,379    [ALTO]
43  HULES DE BALANCIN                      78.0%           959           469    [ALTO]
44  RETENEDORES NJ400-NJ500                77.3%         2,993         1,529    [ALTO]
45  ZAPATAS DE FRENO                       75.7%        19,461        10,573    [ALTO]
46  BRAZOS LOCO Y PITMA,BARRA CENTRAL      73.9%        39,536        21,190    [ALTO]
47  FILTRO AIRE A/C                        72.5%         8,485         4,485    [ALTO]
48  ROL DE EMPUJE                          72.3%        19,443        11,625    [ALTO]
49  ROL DE LA SERIE BALIN                  71.8%        13,301         8,213    [ALTO]
50  TAPA DE DISTIBUIDOR                    71.6%         8,012         4,381    [ALTO]
51  ROL DE CONO Y COPA Y BOCINAS           71.2%        20,621        11,942    [ALTO]
52  ACCESORIOS                             70.5%         9,215         5,477    [ALTO]
53  ANILLOS                                70.2%        26,881        15,254    [ALTO]
54  BOTAS DE EJE Y CREMAYERA               69.6%         7,794         3,820    [ALTO]
55  ROLL EMPUJE                            69.1%        11,129         6,500    [ALTO]
56  UNIONES DE BARRA                       68.9%         9,611         5,155    [ALTO]
57  SOPORTES DE MOTOR Y CAJAS ,TRANFE      68.8%        18,244         9,921    [ALTO]
58  BOMBA AUX DE CLUTCH                    68.7%        17,805         9,515    [ALTO]
59  SENSORES ELECTRICOS                    68.0%        37,652        21,111    [ALTO]
60  BOMBAS PRINCIPAL DE FRENO              67.5%        44,376        24,600    [ALTO]
61  BOCINAS                                66.1%        33,590        18,930    [ALTO]
62  ROL DE GUÍA                            66.0%        15,825         8,220    [ALTO]
63  SILENCIADORES Y MAS                    65.2%        28,739        13,169    [ALTO]
64  PUNTAS DE EJE                          65.1%        28,423        15,777    [ALTO]
65  ESCOBILLAS                             65.0%         6,096         3,494    [ALTO]
66  GALLETAS DE COMPENSADOR                64.9%        13,979         7,701    [ALTO]
67  BOMBA DE GASOLINA                      64.1%        22,717        12,058    [ALTO]
68  FILTROS P/ ACEITE                      63.7%         9,794         5,263    [ALTO]
69  FILTROS AIRE                           63.6%         8,979         5,021    [ALTO]
70  CABLES AUTOMOTRIZ                      63.0%         1,355           833    [ALTO]
71  FLOSSER                                62.6%         2,954         1,709    [ALTO]
72  TIJERETA                               62.4%        40,209        23,374    [ALTO]
73  PORTA CARBONERAS                       61.6%        15,673         9,189    [ALTO]
74  BOMBAS PRINCIPAL DE CLUCHT             58.9%        26,453        14,872    [MEDIO]
75  SOPORTE DE BARRA                       57.7%        21,480        11,890    [MEDIO]
76  FERRETERIA                             53.7%         5,716         3,927    [MEDIO]
77  ADICTIVOS GENERAL                      50.7%         5,121         3,159    [MEDIO]
78  NEUMATICOS Y INICIVOS                  50.5%         5,858         3,652    [MEDIO]
79  LUBRICANTES CHARLY                     48.5%        10,293         6,486    [MEDIO]
80  AMORTIGUADORES                         48.3%        35,384        21,567    [MEDIO]
81  REPUESTOS P/MOTO                       47.2%         6,018         4,092    [MEDIO]
82  REP MOTO                               47.1%         4,211         2,671    [MEDIO]
83  PINTURA SPRAY                          47.0%         2,741         1,718    [MEDIO]
84  FAROLERIA                              46.7%        20,192        13,140    [MEDIO]
85  PLATO DE PRESION                       46.7%        56,953        36,437    [MEDIO]
86  ROL DE DISTRIBUCIÓN                    45.3%        29,888        18,615    [MEDIO]
87  DISCOS Y TAMBOR                        45.0%        25,891        15,830    [MEDIO]
88  REP MOTO R-CHAMORRO                    44.7%        15,171         9,465    [MEDIO]
89  HERRAMIENTAS                           43.2%        13,678         8,772    [MEDIO]
90  DISCO DE CLUTCH                        41.9%        64,489        40,367    [MEDIO]
91  LLANTAS Y NEUMATICOS Y PARCHES         40.1%        19,674        13,615    [MEDIO]
92  LUBRICANTES Y GRASAS                   38.4%        12,090         8,082    [MEDIO]
93  KIT DE BOMBA PRINCIPAL DE FRENO        38.4%        19,425        12,236    [MEDIO]
94  CONSIGNACION DE MOLINA                 35.8%         6,162         4,022    [MEDIO]
95  BATERIAS                               31.3%        67,896        45,342    [BAJO]

RESUMEN DE MARGENES:
  Categorias con margen ALTO  (>=60%):  73
  Categorias con margen MEDIO (35-60%):  21
  Categorias con margen BAJO  (<35%):    1

In [29]:
# ══════════════════ — ARTICULOS PRIORITARIOS PARA LA VICTORIA
# Combina: tiene stock + buen margen + precio accesible
# Estos son los articulos que DEBEN estar el dia 1
# ══════════════════════════════════════════════════

print("ARTICULOS PRIORITARIOS PARA INVENTARIO INICIAL")
print("LA VICTORIA — DIA 1")
print("=" * 70)

# Categorías estratégicas definidas por el análisis
categorias_prioritarias = [
    'FILTROS',
    'PASTILLAS DE FRENO',
    'ELECTRICO',
    'HULES Y BUSHINGS',
    'ROLES',
    'FRENO',
    'CONJUNTO DE CLUTCH',
    'ADICTIVOS',
    'BOMBAS',
    'FAJAS',
    'ROTULAS',
    'RETENEDORES',
    'SENSORES',
]

for cat in categorias_prioritarias:
    # Filtrar artículos de esa categoría con stock y precio válido
    df_cat = df_articulos[
        (df_articulos['Línea'].str.upper().str.contains(cat, na=False)) &
        (df_articulos['Precio venta'] > 0) &
        (df_articulos['%Utilidad'] > 0)
    ].copy()

    if len(df_cat) == 0:
        continue

    total_cat    = len(df_cat)
    con_stock_cat = len(df_cat[df_cat['Inventario'] > 0])
    margen_cat   = df_cat['%Utilidad'].mean()
    precio_cat   = df_cat['Precio venta'].mean()

    print(f"\n  {cat}")
    print(f"  {'-'*50}")
    print(f"  Articulos en catalogo:  {total_cat:>6,}")
    print(f"  Con stock actual:       {con_stock_cat:>6,}")
    print(f"  Margen promedio:        {margen_cat:>6.1f}%")
    print(f"  Precio promedio:        {precio_cat:>10,.0f}")

    # Top 5 articulos de esa categoría por precio de venta
    top5 = df_cat.nlargest(5, 'Precio venta')[
        ['Nombre', 'Precio venta', 'Costo neto', '%Utilidad', 'Inventario']
    ]
    print(f"\n  Top 5 por precio de venta:")
    for _, art in top5.iterrows():
        nombre = str(art['Nombre'])[:55]
        print(f"    - {nombre}")
        print(f"      Precio: {art['Precio venta']:>10,.0f}  "
              f"Costo: {art['Costo neto']:>10,.0f}  "
              f"Margen: {art['%Utilidad']:>6.1f}%  "
              f"Stock: {float(art['Inventario']):>5.0f}")

ARTICULOS PRIORITARIOS PARA INVENTARIO INICIAL
LA VICTORIA — DIA 1
======================================================================

  FILTROS
  --------------------------------------------------
  Articulos en catalogo:     338
  Con stock actual:          188
  Margen promedio:          75.8%
  Precio promedio:            10,478

  Top 5 por precio de venta:
    - RECONSTRUIDASUZUKI SIDECKICK 1,8L 96-98 VITARA 99-08 1,
      Precio:     76,840  Costo:     40,000  Margen:   70.0%  Stock:     0
    - FILTRO DE CAJA AUTOMATICA  TY HILUX, FORTUNE, PRADO
      Precio:     59,435  Costo:     17,000  Margen:  209.4%  Stock:     1
    - Nissan Pickup 2WD (1990-97), Frontier (2006-07)  (Nissa
      Precio:     45,000  Costo:     30,820  Margen:   29.2%  Stock:     0
    - FILTRO SERVICIO PESADO ACEITE HIDRAHULICO new holland 4
      Precio:     45,000  Costo:     23,795  Margen:   67.4%  Stock:     0
    - PATILLA CLUTCH TY RAV4 00-
      Precio:     44,781  Costo:     23,311  Margen:   70.0%  Stock:     0

  PASTILLAS DE FRENO
  --------------------------------------------------
  Articulos en catalogo:     269
  Con stock actual:           80
  Margen promedio:          86.6%
  Precio promedio:            18,223

  Top 5 por precio de venta:
    - PASTILLA L R DISCOVERY -04 DEL
      Precio:     58,800  Costo:     32,800  Margen:   58.6%  Stock:     0
    - PASTILLA DE FRENO DEL INTIMA CITROEN C3
      Precio:     55,000  Costo:     30,100  Margen:   61.7%  Stock:     0
    - PASTILLA DE FRENO DEL ISUZU NPR 88-97 DEL
      Precio:     50,000  Costo:     32,700  Margen:   35.3%  Stock:     0
    - PASTILLA MIT MONTERO SPORT 17-- / L200 20-- DELANT
      Precio:     45,200  Costo:     24,900  Margen:   60.6%  Stock:     0
    - FIBRAS DE FRENO FORD
      Precio:     45,000  Costo:     22,736  Margen:   75.2%  Stock:     0

  ELECTRICO
  --------------------------------------------------
  Articulos en catalogo:     179
  Con stock actual:           17
  Margen promedio:          68.4%
  Precio promedio:            37,706

  Top 5 por precio de venta:
    - SENSOR ACELERADOR TPS NISSAN
      Precio:    135,000  Costo:     74,483  Margen:   60.4%  Stock:     0
    - SENSOR OXIGENO RAV4 BANCA1 ORIGNAL 06/12 AIRE/COMBUSTIB
      Precio:    118,650  Costo:     70,000  Margen:   50.0%  Stock:     0
    - SENSOR DE OXIGENO NS FRONTIER /VERSA
      Precio:    111,900  Costo:     60,000  Margen:   65.0%  Stock:     0
    - SENSOR DE OXIGENO  5L HYUNDAI ACCENT BLUE
      Precio:    110,000  Costo:     65,000  Margen:   49.8%  Stock:     1
    - SENSOR DE OXIGENO TY YARIS 07- BANCO 1
      Precio:    106,500  Costo:     70,000  Margen:   34.6%  Stock:     0

  FRENO
  --------------------------------------------------
  Articulos en catalogo:     866
  Con stock actual:          222
  Margen promedio:          86.7%
  Precio promedio:            16,588

  Top 5 por precio de venta:
    - ABANICO TY COROLLA 7AF
      Precio:     96,300  Costo:      8,243  Margen:  933.9%  Stock:     0
    - BOMBA PRINCIPAL DE FRENO 1-3/16 HYUNDAI MIGHTY
      Precio:     72,073  Costo:     41,325  Margen:   54.3%  Stock:     0
    - Bomba Principal - PATHFINDER DX/SE/ST/XST/XSTXE WD21
      Precio:     70,539  Costo:     36,720  Margen:   70.0%  Stock:     1
    - RADIADOR SUZUKI 2PTS
      Precio:     70,000  Costo:     41,100  Margen:   50.7%  Stock:     0
    - BOMBA PRINCIPAL DE FRENO NS CABSTAR 82-92
      Precio:     69,000  Costo:     43,481  Margen:   40.4%  Stock:     0

  ADICTIVOS
  --------------------------------------------------
  Articulos en catalogo:     258
  Con stock actual:          101
  Margen promedio:          50.9%
  Precio promedio:             5,141

  Top 5 por precio de venta:
    - MAQUINA SUBIR VIDRIO B15 RH
      Precio:     46,000  Costo:     26,542  Margen:   53.4%  Stock:     0
    - Tratamiento Premium para TransmisioÂ´n AutomaÂ´tica - 1
      Precio:     22,800  Costo:     14,434  Margen:   39.8%  Stock:     0
    - AMIGO GALON LIMPIADOR PARA INYECTORES /ESP PARA BANDEJA
      Precio:     20,000  Costo:     13,274  Margen:   33.3%  Stock:     1
    - AMIGO GALON LIQUIDO DE PRUEBA PARA DIAGNOSTICO
      Precio:     20,000  Costo:     13,274  Margen:   33.3%  Stock:     1
    - WC CREMA P/MANOS TARRO/POMEX 4K
      Precio:     15,290  Costo:     10,408  Margen:   30.0%  Stock:     0

  BOMBAS
  --------------------------------------------------
  Articulos en catalogo:      86
  Con stock actual:           13
  Margen promedio:          64.2%
  Precio promedio:            37,499

  Top 5 por precio de venta:
    - BOMBA PRINCIPAL DE FRENO 1-3/16 HYUNDAI MIGHTY
      Precio:     72,073  Costo:     41,325  Margen:   54.3%  Stock:     0
    - BOMBA PRINCIPAL DE CLUTCH FORD F250 F350 7.3 DIESEL  /9
      Precio:     71,500  Costo:     40,697  Margen:   55.5%  Stock:     0
    - Bomba Principal - PATHFINDER DX/SE/ST/XST/XSTXE WD21
      Precio:     70,539  Costo:     36,720  Margen:   70.0%  Stock:     1
    - BOMBA PRINCIPAL DE FRENO NS CABSTAR 82-92
      Precio:     69,000  Costo:     43,481  Margen:   40.4%  Stock:     0
    - BOMBA PRINCIPAL DE FRENO TY 4RUNNER/HILUX   4 TORNILLO
      Precio:     66,000  Costo:     45,000  Margen:   29.8%  Stock:     0

  FAJAS
  --------------------------------------------------
  Articulos en catalogo:     399
  Con stock actual:          125
  Margen promedio:          83.8%
  Precio promedio:            10,651

  Top 5 por precio de venta:
    - KIT DISTRIBUCION CHEVROLET S10 82/93
      Precio:     70,000  Costo:     20,825  Margen:  197.5%  Stock:     0
    - KIT DE DISTRIBUCION NISSAN GA16 DOHC 16 VAL 91
      Precio:     67,576  Costo:     44,248  Margen:   35.1%  Stock:     0
    - FAJA DISTRI KIA CARNIVAL LS
      Precio:     62,400  Costo:      9,730  Margen:  467.5%  Stock:     0
    - FAJA UNICA BOBCAT
      Precio:     58,500  Costo:     39,823  Margen:   30.0%  Stock:     0
    - TENSOR HIDRA FAJA UNICA 05- J24 GRAN VITARA
      Precio:     41,000  Costo:     27,328  Margen:   32.8%  Stock:     0

  ROTULAS
  --------------------------------------------------
  Articulos en catalogo:     533
  Con stock actual:          222
  Margen promedio:         101.5%
  Precio promedio:            14,822

  Top 5 por precio de venta:
    - TIJERETA RH NISSAN X-TRAIL
      Precio:    102,000  Costo:     62,165  Margen:   45.2%  Stock:     0
    - TIJERETA LH NISSAN X-TRAIL
      Precio:     91,600  Costo:     55,898  Margen:   45.0%  Stock:     0
    - BRAZO DE DIRECCION LATERAL NQR
      Precio:     84,265  Costo:     57,362  Margen:   30.0%  Stock:     0
    - TIJERETA INF SZ VITARA IZQUIRDA 00-
      Precio:     75,055  Costo:     36,900  Margen:   80.0%  Stock:     0
    - TIJERETA LH SUZUKI VITARA 99-02
      Precio:     68,000  Costo:     39,114  Margen:   53.9%  Stock:     0

  RETENEDORES
  --------------------------------------------------
  Articulos en catalogo:     401
  Con stock actual:          184
  Margen promedio:         114.6%
  Precio promedio:             6,242

  Top 5 por precio de venta:
    - RETENEDOR COMPLETO ZD30 CIGUEÑAL TRASERO
      Precio:    105,000  Costo:     22,124  Margen:  320.0%  Stock:     0
    - RETENEDOR HIDRAULICO 16X40X8
      Precio:     80,000  Costo:      2,000  Margen: 3439.8%  Stock:     1
    - Base y Retenedor Volante 2.0TDI AMARO
      Precio:     60,000  Costo:     36,876  Margen:   44.0%  Stock:     0
    - SENSOR OXIGENO BANCO 1 HONDA CRV MARCA STANDARD AMERICA
      Precio:     51,000  Costo:     32,520  Margen:   38.8%  Stock:     0
    - ASPIRAL TRASERA MIT MONTERO SPORT
      Precio:     45,589  Costo:     33,620  Margen:   20.0%  Stock:     0

  SENSORES
  --------------------------------------------------
  Articulos en catalogo:     179
  Con stock actual:           17
  Margen promedio:          68.4%
  Precio promedio:            37,706

  Top 5 por precio de venta:
    - SENSOR ACELERADOR TPS NISSAN
      Precio:    135,000  Costo:     74,483  Margen:   60.4%  Stock:     0
    - SENSOR OXIGENO RAV4 BANCA1 ORIGNAL 06/12 AIRE/COMBUSTIB
      Precio:    118,650  Costo:     70,000  Margen:   50.0%  Stock:     0
    - SENSOR DE OXIGENO NS FRONTIER /VERSA
      Precio:    111,900  Costo:     60,000  Margen:   65.0%  Stock:     0
    - SENSOR DE OXIGENO  5L HYUNDAI ACCENT BLUE
      Precio:    110,000  Costo:     65,000  Margen:   49.8%  Stock:     1
    - SENSOR DE OXIGENO TY YARIS 07- BANCO 1
      Precio:    106,500  Costo:     70,000  Margen:   34.6%  Stock:     0

In [31]:
# ═════════════ — LOS 50 ARTICULOS INDISPENSABLES
# Criterios de selección:
# 1. Categorías de alta rotación del negocio de referencia
# 2. Margen entre 20% mínimo y sin techo máximo
# 3. Aplicación a las marcas predominantes del mercado
# 4. Cubre los 3 tipos de cliente (dueño, mecánico, taller)
# ══════════════════════════════════════════════════

import pandas as pd

# Filtrar artículos con condiciones mínimas de calidad
df_validos = df_articulos[
    (df_articulos['Precio venta'] > 0) &
    (df_articulos['Costo neto'] > 0) &
    (df_articulos['%Utilidad'] >= 20) &
    (df_articulos['Estado'] == 'Activo')
].copy()

# Definir categorías prioritarias con su peso estratégico
categorias_peso = {
    'FILTROS':               10,
    'PASTILLAS DE FRENO':     8,
    'FRENO':                  7,
    'CONJUNTO DE CLUTCH':     7,
    'ELECTRICO':              6,
    'HULES Y BUSHINGS':       6,
    'ROLES':                  5,
    'ADICTIVOS':              5,
    'BOMBAS':                 5,
    'FAJAS':                  4,
    'ROTULAS':                4,
    'RETENEDORES':            4,
    'SENSORES':               3,
    'EMPAQUES':               3,
}

seleccionados = []

for categoria, cupo in categorias_peso.items():
    df_cat = df_validos[
        df_validos['Línea'].str.contains(categoria, na=False)
    ].copy()

    if len(df_cat) == 0:
        continue

    # Dentro de cada categoría, priorizar por margen alto
    # y precio de venta razonable (accesible para el cliente)
    df_cat = df_cat.sort_values(
        ['%Utilidad', 'Precio venta'], 
        ascending=[False, True]
    ).head(cupo)

    df_cat['Categoria'] = categoria
    seleccionados.append(df_cat)

df_top50 = pd.concat(seleccionados, ignore_index=True)
df_top50 = df_top50.head(50)

# Agregar número de orden
df_top50.insert(0, 'N', range(1, len(df_top50) + 1))

print("LOS 50 ARTICULOS INDISPENSABLES — TOTAL AUTOMOTRIZ LA VICTORIA")
print("=" * 90)
print(f"\n{'N':<4} {'Categoria':<25} {'Articulo':<45} {'Precio':>10} {'Margen':>8}")
print("-" * 95)

for _, row in df_top50.iterrows():
    nombre = str(row['Nombre'])[:43]
    cat    = str(row['Categoria'])[:23]
    print(f"{int(row['N']):<4} {cat:<25} {nombre:<45} "
          f"  {row['Precio venta']:>8,.0f}  "
          f"{row['%Utilidad']:>7.1f}%")

print(f"\nTOTAL ARTICULOS SELECCIONADOS: {len(df_top50)}")
print(f"Margen promedio de la seleccion: {df_top50['%Utilidad'].mean():.1f}%")
print(f"Precio promedio de la seleccion: {df_top50['Precio venta'].mean():,.0f}")
print(f"Inversion estimada en inventario inicial:")
inversion = (df_top50['Costo neto'] * 1).sum()
print(f"  (1 unidad por articulo): {inversion:>12,.0f}")
print(f"  (2 unidades por articulo): {inversion*2:>12,.0f}")
print(f"  (3 unidades por articulo): {inversion*3:>12,.0f}")

LOS 50 ARTICULOS INDISPENSABLES — TOTAL AUTOMOTRIZ LA VICTORIA
==========================================================================================

N    Categoria                 Articulo                                          Precio   Margen
-----------------------------------------------------------------------------------------------
1    FILTROS                   BASE DE BOMBILLOS TODO VIDRIO C/CABLE              2,000   1669.9%
2    FILTROS                   FILTRO ACEITE PH2808/PH3593 ALTO KILOMETRAJ        8,500    599.1%
3    FILTROS                   Empaque Cabezot - FRONTIER VG33E D22 (98/05       26,000    360.2%
4    FILTROS                   FILTRO AIRE ACONDICIONADO CABINA NISSAN TIL        9,000    296.4%
5    FILTROS                   ROTULA  ROT.DIR. LH-RH EXT / HONDA-CR-V 4X2       13,000    265.2%
6    FILTROS                   FILTRO DE COMBUSTIBLE LFF5950                      7,800    245.1%
7    FILTROS                   FILTRO DE COMBUSTIBLE LP-5597                      5,800    242.2%
8    FILTROS                   FILTRO DIECEL BF-215/9-13240-032-0 NISSAN J        3,800    236.3%
9    FILTROS                   FILTRO AF1189 1378078R00 AIRE SUZUKI JIMMY         7,500    234.4%
10   FILTROS                   ROTULA SUS. LH INF / HONDA-CR-V 4X2 07-11         13,000    221.2%
11   PASTILLAS DE FRENO        PASTILLA DEL KIA SPECTRA 02-                      23,800   2006.2%
12   PASTILLAS DE FRENO        PASTILLA DE FRENO TRASERO FORD F150               37,500    360.9%
13   PASTILLAS DE FRENO        PASTILLA DE FRENO CERAMICA TRAS MIT MONTERO       14,000    299.7%
14   PASTILLAS DE FRENO        PASTILLA DE FRENO   NISSAN ALMERA                 18,000    298.2%
15   PASTILLAS DE FRENO        PASTILLA DE FRENO DELANTERA CHEVROLET AVALA       31,000    278.1%
16   PASTILLAS DE FRENO        Pastillas Freno - SWIFT RS413GL/RS413GA/RS4       20,000    260.6%
17   PASTILLAS DE FRENO        PASTILLA DE FRENO CERAMICA   HY TUCSON /KIA       24,500    237.1%
18   PASTILLAS DE FRENO        PASTILLA FRENO  SUBARU LEGACY 00-09 FORESTE       15,000    218.7%
19   FRENO                     PASTILLA DEL KIA SPECTRA 02-                      23,800   2006.2%
20   FRENO                     ZAPATA TRAS KIA SPECTRA 02-                       14,800   1209.7%
21   FRENO                     ABANICO TY COROLLA 7AF                            96,300    933.9%
22   FRENO                     LAMINA NONASBESTO SIN MALLA 1/31 0.08              5,000    785.0%
23   FRENO                     LAMINA NONASBESTO SIN MALLA 1/6 00.4                 120    608.0%
24   FRENO                     GUARNITAL VELLOMOVIL 1/64 0.4MM                      142    498.4%
25   FRENO                     MANGUERA CURVA P/PASO DE ACEITE                    9,000    400.0%
26   ELECTRICO                 SENSOR DE CIGUENAL KA24 12 VALVU                  40,000    268.7%
27   ELECTRICO                 SENSOR DE VELOCIDAD HY/KIA-                       11,000    214.7%
28   ELECTRICO                 SENSOR TEMPAGUA SPARKAVEOOPTRA 08                  6,900    177.1%
29   ELECTRICO                 SENSOR POSICION CIGUEñAL STA FE 00-               33,800    157.9%
30   ELECTRICO                 SENSOR TEMPERATURA DE COOLAN SZ SIDEKICK 16        9,000    157.9%
31   ELECTRICO                 SENSOR TEMPERARATURA BEETLE/JETTA/GOLF/PASS       12,000    156.5%
32   ADICTIVOS                 ARTICULOS DE ASEO                                 10,300    811.5%
33   ADICTIVOS                 LAMINA NONASBESTO SIN MALLA 1/32 0.08                155    496.4%
34   ADICTIVOS                 NAIS SHINI GALON EL AMIGO                         10,600    430.0%
35   ADICTIVOS                 COOLANT SABO 10% GALON ANTICORROSIVO               3,350    168.0%
36   ADICTIVOS                 LIMPIADOR INTERNO DE MOTOR 150Z                    4,000    116.7%
37   BOMBAS                    SET DE REPARACION BOMBA PRINCIPAL DE FRENOS       24,800    324.2%
38   BOMBAS                    BOMBA PRINCIPAL DE FRENO TY MODEL-F               45,000    165.5%
39   BOMBAS                    BOMBA PRINCIPAL DE FRENO TY BJ40 LAND CRUSS       57,800    155.8%
40   BOMBAS                    BOMBA PRINC  CLUTCH RAV4 95/05                    21,500    115.2%
41   BOMBAS                    BOMBA PRINCIPAL DE FRENO TY 4RUNNER/HILUX         53,800    113.5%
42   FAJAS                     FAJA DISTRI KIA CARNIVAL LS                       62,400    467.5%
43   FAJAS                     FAJA 8PK1450                                      18,500    411.6%
44   FAJAS                     FAJA OPEL CORSA                                   28,300    400.9%
45   FAJAS                     FAJA 6PK2110 ALTERNADOR                            8,000    372.0%
46   ROTULAS                   ROTULA SB2502 SUSP SUPERIOR TY MOVEL F 82-         8,000   3500.0%
47   ROTULAS                   ROTULA SUSPENCION NISSAN URVAN 10-                63,500   1247.8%
48   ROTULAS                   ROTULA CREMALLERA HD CIVI 88-91                    7,800    475.2%
49   ROTULAS                   ROTULA DIRECION INT  D21 4WD PATHFINDER 92-        8,500    370.1%
50   RETENEDORES               RETENEDOR HIDRAULICO 16X40X8                      80,000   3439.8%

TOTAL ARTICULOS SELECCIONADOS: 50
Margen promedio de la seleccion: 589.7%
Precio promedio de la seleccion: 21,167
Inversion estimada en inventario inicial:
  (1 unidad por articulo):      211,000
  (2 unidades por articulo):      421,999
  (3 unidades por articulo):      632,999

In [32]:
# ═════════════════ ARTICULOS MAS VENDIDOS
# Metodologia: Rotacion de stock
# Logica: Si un articulo tiene stock en 0 o muy bajo,
# es porque se vendio. Los que mas se agotaron
# son los que mas demanda tuvieron en el mercado.
# ══════════════════════════════════════════════════

print("ARTICULOS MAS VENDIDOS POR ROTACION DE STOCK")
print("Negocio de referencia — Rio Frio")
print("=" * 75)

# Clasificar cada articulo por nivel de stock
def clasificar_stock(inv):
    if inv == 0:
        return 'AGOTADO — Alta rotacion'
    elif inv <= 2:
        return 'CRITICO — Rotacion alta'
    elif inv <= 5:
        return 'BAJO — Rotacion media'
    else:
        return 'DISPONIBLE — Rotacion normal'

df_articulos['nivel_stock'] = df_articulos['Inventario'].apply(clasificar_stock)

# Contar por nivel
resumen_stock = df_articulos.groupby('nivel_stock').agg(
    cantidad = ('Código', 'count'),
).reset_index()
resumen_stock['porcentaje'] = (
    resumen_stock['cantidad'] / len(df_articulos) * 100
).round(1)

print(f"\nDISTRIBUCION GENERAL DE STOCK:")
print(f"  {'Nivel':<35} {'Articulos':>10} {'Porcentaje':>12}")
print(f"  {'-'*60}")
for _, row in resumen_stock.iterrows():
    print(f"  {row['nivel_stock']:<35} {int(row['cantidad']):>10,} {row['porcentaje']:>11.1f}%")

# Articulos agotados con buen margen — estos son los que mas rotaron
df_agotados = df_articulos[
    (df_articulos['Inventario'] == 0) &
    (df_articulos['%Utilidad'] >= 20) &
    (df_articulos['Precio venta'] > 0) &
    (df_articulos['Estado'] == 'Activo')
].copy()

print(f"\n  Total articulos agotados con margen >= 20%: {len(df_agotados):,}")
print(f"  Estos son los candidatos de mayor rotacion")

ARTICULOS MAS VENDIDOS POR ROTACION DE STOCK
Negocio de referencia — Rio Frio
===========================================================================

DISTRIBUCION GENERAL DE STOCK:
  Nivel                                Articulos   Porcentaje
  ------------------------------------------------------------
  AGOTADO — Alta rotacion                  6,560        64.8%
  BAJO — Rotacion media                      483         4.8%
  CRITICO — Rotacion alta                  2,567        25.4%
  DISPONIBLE — Rotacion normal               506         5.0%

  Total articulos agotados con margen >= 20%: 6,211
  Estos son los candidatos de mayor rotacion

In [33]:
# ═════════ TOP ARTICULOS AGOTADOS POR CATEGORIA
# Agotado + buen margen = alta rotacion real
# Estos son exactamente los que La Victoria
# debe tener siempre en stock
# ══════════════════════════════════════════════════

print("TOP ARTICULOS AGOTADOS POR CATEGORIA")
print("Estos son los que mas rotaron en el negocio de referencia")
print("=" * 80)

categorias_analizar = [
    'FILTROS',
    'PASTILLAS DE FRENO',
    'FRENO',
    'CONJUNTO DE CLUTCH',
    'ELECTRICO',
    'HULES Y BUSHINGS',
    'ROLES',
    'ADICTIVOS',
    'BOMBAS',
    'FAJAS',
    'ROTULAS',
    'RETENEDORES',
    'EMPAQUES',
    'SENSORES',
]

resultado_categorias = []

for categoria in categorias_analizar:
    df_cat = df_agotados[
        df_agotados['Línea'].str.contains(categoria, na=False)
    ].copy()

    if len(df_cat) == 0:
        continue

    total_agotados = len(df_cat)
    margen_prom    = df_cat['%Utilidad'].mean()
    precio_prom    = df_cat['Precio venta'].mean()

    resultado_categorias.append({
        'Categoria':       categoria,
        'Agotados':        total_agotados,
        'Margen_prom':     margen_prom,
        'Precio_prom':     precio_prom,
    })

df_resultado = pd.DataFrame(resultado_categorias)
df_resultado = df_resultado.sort_values('Agotados', ascending=False).reset_index(drop=True)

print(f"\n{'#':<3} {'Categoria':<28} {'Agotados':>9} {'Margen Prom':>12} {'Precio Prom':>12}")
print(f"  {'-'*68}")

for i, row in df_resultado.iterrows():
    print(f"  {i+1:<3} {row['Categoria']:<28} "
          f"{int(row['Agotados']):>9,} "
          f"{row['Margen_prom']:>11.1f}% "
          f"  {row['Precio_prom']:>10,.0f}")

TOP ARTICULOS AGOTADOS POR CATEGORIA
Estos son los que mas rotaron en el negocio de referencia
================================================================================

#   Categoria                     Agotados  Margen Prom  Precio Prom
  --------------------------------------------------------------------
  1   FRENO                              594        86.7%       18,311
  2   ROTULAS                            300        82.9%       18,197
  3   FAJAS                              268        81.9%       12,204
  4   RETENEDORES                        198        98.9%        7,964
  5   PASTILLAS DE FRENO                 184        89.5%       19,128
  6   SENSORES                           155        69.7%       39,317
  7   ELECTRICO                          155        69.7%       39,317
  8   FILTROS                            148        83.1%       13,771
  9   ADICTIVOS                          131        52.5%        5,693
  10  EMPAQUES                           116       100.0%       14,084
  11  BOMBAS                              69        65.5%       38,047

In [34]:
# ═══════════════ DETALLE DE ARTICULOS POR CATEGORIA
# Top 10 articulos agotados de cada categoria
# ordenados por margen de utilidad
# ══════════════════════════════════════════════════

print("DETALLE DE ARTICULOS AGOTADOS POR CATEGORIA")
print("Top 10 por categoria — ordenados por margen")
print("=" * 80)

for categoria in categorias_analizar:
    df_cat = df_agotados[
        df_agotados['Línea'].str.contains(categoria, na=False)
    ].sort_values('%Utilidad', ascending=False).head(10)

    if len(df_cat) == 0:
        continue

    print(f"\n  {categoria}")
    print(f"  {'-'*75}")
    print(f"  {'Articulo':<50} {'Precio':>10} {'Margen':>8}")
    print(f"  {'-'*75}")

    for _, row in df_cat.iterrows():
        nombre = str(row['Nombre'])[:48]
        print(f"  {nombre:<50} "
              f"  {row['Precio venta']:>8,.0f} "
              f"  {row['%Utilidad']:>6.1f}%")

DETALLE DE ARTICULOS AGOTADOS POR CATEGORIA
Top 10 por categoria — ordenados por margen
================================================================================

  FILTROS
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  BASE DE BOMBILLOS TODO VIDRIO C/CABLE                   2,000   1669.9%
  FILTRO ACEITE PH2808/PH3593 ALTO KILOMETRAJE            8,500    599.1%
  ROTULA  ROT.DIR. LH-RH EXT / HONDA-CR-V 4X2 07-1       13,000    265.2%
  FILTRO DE COMBUSTIBLE LP-5597                           5,800    242.2%
  FILTRO DIECEL BF-215/9-13240-032-0 NISSAN JUNIOR        3,800    236.3%
  ROTULA SUS. LH INF / HONDA-CR-V 4X2 07-11              13,000    221.2%
  FILTRO AIRE HY CRETA                                   14,500    185.2%
  FILTRO CAJA AUTOMATICA MB MONTERO SPORT                18,000    183.9%
  BOCINA DEL. NISSAN B12                                 23,500    181.0%
  FILTRO COMBUSTIBLE FOR G3802A                          12,500    155.1%

  PASTILLAS DE FRENO
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  PASTILLA DEL KIA SPECTRA 02-                           23,800   2006.2%
  PASTILLA DE FRENO TRASERO FORD F150                    37,500    360.9%
  PASTILLA DE FRENO DELANTERA CHEVROLET AVALANCHE        31,000    278.1%
  Pastillas Freno - SWIFT RS413GL/RS413GA/RS415GL        20,000    260.6%
  PASTILLA FRENO  SUBARU LEGACY 00-09 FORESTE 98-0       15,000    218.7%
  PASTILLA FRENO TRASERA CHEVROLET AVALANCHE 2007        25,000    199.8%
  DISC BRAKE HARDWARE KIT D8629 DMAX 4X4 2017            10,900    192.3%
  DISCO DE FRENO DELANTERO VENTILADO VITARA 16-19        43,737    185.5%
  PASTILLA FRENO  KIA/MAZDA 323/FOR                      12,900    185.4%
  PASTILLA DE FRENO DAIHATSU CHARADE 88-92                9,500    180.2%

  FRENO
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  PASTILLA DEL KIA SPECTRA 02-                           23,800   2006.2%
  ZAPATA TRAS KIA SPECTRA 02-                            14,800   1209.7%
  ABANICO TY COROLLA 7AF                                 96,300    933.9%
  LAMINA NONASBESTO SIN MALLA 1/31 0.08                   5,000    785.0%
  LAMINA NONASBESTO SIN MALLA 1/6 00.4                      120    608.0%
  PASADOR VARIOS                                            750    392.6%
  PASTILLA DE FRENO TRASERO FORD F150                    37,500    360.9%
  SET DE REPARACION BOMBA PRINCIPAL DE FRENOS 1 1/       24,800    324.2%
  CABLE CLUTCH DEAWOO MATIZ/ CHEVROLET SPARK 98-20       15,600    291.0%
  PASTILLA DE FRENO DELANTERA CHEVROLET AVALANCHE        31,000    278.1%

  ELECTRICO
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  SENSOR DE CIGUENAL KA24 12 VALVU                       40,000    268.7%
  SENSOR DE VELOCIDAD HY/KIA-                            11,000    214.7%
  SENSOR TEMPAGUA SPARKAVEOOPTRA 08                       6,900    177.1%
  SENSOR POSICION CIGUEñAL STA FE 00-                    33,800    157.9%
  SENSOR TEMPERATURA DE COOLAN SZ SIDEKICK 16             9,000    157.9%
  SENSOR TEMPERARATURA BEETLE/JETTA/GOLF/PASSAT/PO       12,000    156.5%
  SENSOR COOLANT GOLF/JETTA A3/ VANAGON 2006/2009        12,000    143.3%
  BULBO TEMPERATURA 2/3A/1/2/3Y/BJ70/L/2L. TERCEL-        4,500    138.3%
  SENSOR DE ARVOL DE LEVAS HY TERRACAN 2.9               18,500    133.9%
  SENSOR TEMPERATURA COOLANT ACCENT VERNA/ALFA 00-       49,000    128.2%

  ADICTIVOS
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  ARTICULOS DE ASEO                                      10,300    811.5%
  LAMINA NONASBESTO SIN MALLA 1/32 0.08                     155    496.4%
  LIQUIDO FRENOS 946ML LITRO DOT-4 MANNOL                 5,800     98.6%
  CERA PARA CARRO NEGRA 473ML ABRO                        7,000     96.0%
  ESPUMA LIMPIEZA MULTIUSO 650 ML                         2,300     86.1%
  ADITIVO DIESEL ALL IN ONE FUEL SYSTEM CLEANER, T        6,500     85.6%
  GOLDEN SUPREME 2 TIEMPOS ENGINE OIL 12/1QT              3,000     77.0%
  ULTRA CLEANER PEQUEÑO                                     500     75.1%
  COOLANT REFRIGERANTE ANTIC GALON                        2,800     75.0%
  CERA VERDE 16oz ABRO                                    5,577     70.0%

  BOMBAS
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  SET DE REPARACION BOMBA PRINCIPAL DE FRENOS 1 1/       24,800    324.2%
  BOMBA PRINCIPAL DE FRENO TY MODEL-F                    45,000    165.5%
  BOMBA PRINC  CLUTCH RAV4 95/05                         21,500    115.2%
  BOMBA PRINCIPAL DE FRENO TY 4RUNNER/HILUX   4 TO       53,800    113.5%
  Bomba Principal  B2600 (90/96) bt50                    28,900    110.2%
  BOMBA PRINCIPAL DE FRENO NISSAN VANNET                 49,600    109.1%
  Bomba Principal - FEROZA (90/00)                       57,000     96.4%
  BOMBA PRINCIPAL DE FRENO MAZDA  B2000/B2200 2WD        39,000     96.2%
  BOMBA PRINCIPAL DE CLUTCH TERIUS BEGO 5/8              26,200     93.2%
  BOMBA PRIN DE CLUT HY ELANTRA AVANTE 96-               17,500     88.8%

  FAJAS
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  FAJA DISTRI KIA CARNIVAL LS                            62,400    467.5%
  FAJA 6PK2110 ALTERNADOR                                 8,000    372.0%
  FAJA 6PK1310 ALTERNADOR                                 6,000    254.0%
  FAJA DISTRIBUCION 113D/                                 7,500    231.9%
  FAJA 3PK975 38.5\ ALT TY TERCEL 83- MOTOR 4A"           8,500    216.9%
  FAJA DISTRIBUCION 109 DIENTES  MZ B2000 B2200 84       10,800    216.2%
  FAJA AUTOMOTRIZ EN -V-                                  5,600    208.6%
  KIT DISTRIBUCION CHEVROLET S10 82/93                   70,000    197.5%
  FAJA 4PK1085                                            6,000    183.2%
  FAJA SERPENTINA SANTA FE/ TUCSON 6PK2000               16,000    167.2%

  ROTULAS
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  ROTULA SUSPENCION NISSAN URVAN 10-                     63,500   1247.8%
  ROTULA CREMALLERA HD CIVI 88-91                         7,800    475.2%
  ROTULA  SB2992 DE SUSPENCION   TY CORONA/CELICA        13,800    339.2%
  ROTULA DE CREMALLERA TY RAV4 00-03                     13,500    303.8%
  ROTULA DE CREMALLERA TY/COROLLA EA86 HIDRAULICA        13,000    283.5%
  ROTULA DIRECION EX MZ 323 , PROTEGE 89-98              15,500    243.6%
  ROTULA SB2292 SUSPENCION TY CRESSIA                    19,210    240.0%
  TERMINAL INT CONTOUR 1995-1997 / CO                    28,250    239.1%
  ROTULA SUS. RH INF / HONDA-CR-V 4X2 07-11              13,000    221.2%
  ROTULA DIRECION EXT SE1541 MZ B2500/B2600  4X4 8       12,500    218.4%

  RETENEDORES
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  Retenedor Cigueñal (41x56x8) J35 V6 HD Pilot           11,322    518.5%
  RETENEDOR MIDE 35X56X8.9X16.4 DIFERENCIAL TRASER        9,000    431.0%
  RETENEDOR MIDE 88X106X8.7                               8,800    419.2%
  Retenedor Arbol Levas (39x53x8) J35 Ex ExL Lx Rt        9,040    402.8%
  RETENEDOR CIGUANAL DELANTERO  HY ACCENT 2011- G4        3,700    347.1%
  RETENEDOR MIDE 35X50X11 - 32136-U0100  NCP/  JAP        7,500    342.5%
  RETENEDOR CIGUENAL DELANTERO                           12,500    342.5%
  RETENEDOR MIDE 27X43X7 MAZDA/ HONDA SELLO MANUAL        4,800    323.9%
  RETENEDOR COMPLETO ZD30 CIGUEÑAL TRASERO              105,000    320.0%
  RETENEDOR MIDE 35X47X6                                  5,800    286.8%

  EMPAQUES
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  Empaque Manifol - ADMISION  RAV4 1AZFE/2AZFE ACA        6,000    396.7%
  EMPAQUE ADMISION Manifol - B210/B310 datsun A12         6,500    387.5%
  EMPAQUE CABEZOTE CHEVROLET AVEO 2010-                  15,000    342.5%
  EMPAQUE CABEZOTE MAZDA B2600 G6                        19,000    331.6%
  Empaque Manifol - YARIS 1NZFE/2NZFE (99/17), GRE        4,500    314.0%
  EMPAQUE CABEZOTE HY SANTA FE 2.4/SONATA                14,000    262.4%
  EMPAQUE CABEZOTE NISSAN QD32                           19,748    242.7%
  EMPAQUE MULTIPLE ADMISION ELANTRA 1.8CC - TUCSON        2,500    240.4%
  EMPAQUE CABEZOTE VITARA/GRAN VITARA J20A 98-05 S       11,500    211.7%
  EMPAQUE CABEZOTE A14 Nissan-datsun                      9,500    196.6%

  SENSORES
  ---------------------------------------------------------------------------
  Articulo                                               Precio   Margen
  ---------------------------------------------------------------------------
  SENSOR DE CIGUENAL KA24 12 VALVU                       40,000    268.7%
  SENSOR DE VELOCIDAD HY/KIA-                            11,000    214.7%
  SENSOR TEMPAGUA SPARKAVEOOPTRA 08                       6,900    177.1%
  SENSOR POSICION CIGUEñAL STA FE 00-                    33,800    157.9%
  SENSOR TEMPERATURA DE COOLAN SZ SIDEKICK 16             9,000    157.9%
  SENSOR TEMPERARATURA BEETLE/JETTA/GOLF/PASSAT/PO       12,000    156.5%
  SENSOR COOLANT GOLF/JETTA A3/ VANAGON 2006/2009        12,000    143.3%
  BULBO TEMPERATURA 2/3A/1/2/3Y/BJ70/L/2L. TERCEL-        4,500    138.3%
  SENSOR DE ARVOL DE LEVAS HY TERRACAN 2.9               18,500    133.9%
  SENSOR TEMPERATURA COOLANT ACCENT VERNA/ALFA 00-       49,000    128.2%

In [35]:
# ═══════════════════════ RESUMEN EJECUTIVO
# Conclusion del analisis de rotacion
# ══════════════════════════════════════════════════

print("RESUMEN EJECUTIVO — ANALISIS DE ROTACION")
print("=" * 65)

total_activos  = len(df_articulos[df_articulos['Estado'] == 'Activo'])
total_agotados = len(df_agotados)
pct_agotados   = total_agotados / total_activos * 100

print(f"\n  Total articulos activos:          {total_activos:>8,}")
print(f"  Articulos agotados con margen:    {total_agotados:>8,}")
print(f"  Porcentaje agotado:               {pct_agotados:>8.1f}%")

print(f"\n  CATEGORIA MAS AGOTADA (mayor rotacion):")
top_cat = df_resultado.iloc[0]
print(f"  {top_cat['Categoria']}")
print(f"  {int(top_cat['Agotados'])} articulos agotados")
print(f"  Margen promedio: {top_cat['Margen_prom']:.1f}%")

print(f"\n  CONCLUSION PARA LA VICTORIA:")
print(f"  Las categorias con mayor rotacion deben tener")
print(f"  stock permanente minimo de 2 a 3 unidades por articulo.")
print(f"  Los articulos agotados en el negocio de referencia")
print(f"  son exactamente los que La Victoria debe priorizar")
print(f"  en su inventario inicial.")

print(f"\n  INVERSION ESTIMADA EN STOCK MINIMO:")
inversion_min = (df_agotados['Costo neto'].sum()) * 1
inversion_rec = (df_agotados['Costo neto'].sum()) * 2
print(f"  1 unidad por articulo agotado:   {inversion_min:>12,.0f}")
print(f"  2 unidades por articulo agotado: {inversion_rec:>12,.0f}")

RESUMEN EJECUTIVO — ANALISIS DE ROTACION
=================================================================

  Total articulos activos:            10,094
  Articulos agotados con margen:       6,211
  Porcentaje agotado:                   61.5%

  CATEGORIA MAS AGOTADA (mayor rotacion):
  FRENO
  594 articulos agotados
  Margen promedio: 86.7%

  CONCLUSION PARA LA VICTORIA:
  Las categorias con mayor rotacion deben tener
  stock permanente minimo de 2 a 3 unidades por articulo.
  Los articulos agotados en el negocio de referencia
  son exactamente los que La Victoria debe priorizar
  en su inventario inicial.

  INVERSION ESTIMADA EN STOCK MINIMO:
  1 unidad por articulo agotado:     82,663,204
  2 unidades por articulo agotado:  165,326,409

In [38]:
# ══════════════════════════════════════════════════
# CELDA 22 — ARTICULOS CRITICOS DE EMERGENCIA
# Definicion: El cliente los necesita hoy.
# Si no los tenes, se va a la competencia.
# Orden de criticidad definido por experiencia
# del propietario de La Victoria.
# ══════════════════════════════════════════════════

print("ANALISIS 3 — ARTICULOS CRITICOS DE EMERGENCIA")
print("Total Automotriz La Victoria")
print("=" * 75)

# ── DEFINICION DE GRUPOS CRITICOS ──────────────────
# Orden: 1=mas critico, 4=menos critico
grupos_criticos = {

    1: {
        'nombre'     : 'GRUPO 1 — EL VEHICULO NO ARRANCA',
        'descripcion': 'El cliente no puede moverse. Necesita solucion inmediata.',
        'keywords'   : [
            'BOMBA COMBUSTIBLE', 'BOMBA DE COMBUSTIBLE',
            'ALTERNADOR', 'AUTOMATICO', 'ARRANC',
            'RELAY', 'RELE', 'FUSIBLE',
            'BUJIA', 'BOBINA', 'DISTRIBUIDOR',
            'CABLE BUJIA', 'PLATINO', 'CONDENSADOR',
            'CARBON ARRANC', 'CARBON ALTERN',
            'REGULADOR', 'PORTA CARBON',
        ]
    },

    2: {
        'nombre'     : 'GRUPO 2 — EL VEHICULO NO FRENA',
        'descripcion': 'Riesgo de seguridad inmediato. No puede circular.',
        'keywords'   : [
            'PASTILLA', 'ZAPATA', 'TAMBOR',
            'DISCO DE FRENO', 'CILINDRO DE FRENO',
            'CILINDRO RUEDA', 'CILINDRO MAESTRO',
            'LIQUIDO DE FRENO', 'LIQUIDO FRENOS',
            'MANGUERA DE FRENO', 'MANGUERA FRENO',
            'EMPAQUE FRENO', 'KIT FRENO',
            'SERVO FRENO', 'BOSTER',
        ]
    },

    3: {
        'nombre'     : 'GRUPO 3 — EL VEHICULO NO TRANSMITE POTENCIA',
        'descripcion': 'El vehiculo avanza mal o no avanza. No es util para el cliente.',
        'keywords'   : [
            'BOTA DE EJE', 'BOTA EJE', 'BOTA INT',
            'CRUCETA', 'RODAMIENTO RUEDA', 'ROLL',
            'KIT CLUTCH', 'CONJUNTO CLUTCH', 'PLATO CLUTCH',
            'DISCO CLUTCH', 'COLLARÍN', 'COLARIN',
            'CAJA VELOCIDAD', 'SINCRONIZADO',
            'DIFERENCIAL', 'CATALINA',
        ]
    },

    4: {
        'nombre'     : 'GRUPO 4 — EL VEHICULO PIERDE FLUIDOS',
        'descripcion': 'Si no se atiende a tiempo puede generar daño mayor al motor.',
        'keywords'   : [
            'EMPAQUE CULATA', 'JUNTA CULATA',
            'EMPAQUE TAPA VALVULA', 'EMPAQUE CARTER',
            'RETENEDOR', 'SELLO', 'RETÉN',
            'MANGUERA RADIADOR', 'TAPON RADIADOR',
            'TAPON CARTER', 'TAPON ACEITE',
            'BOMBA AGUA', 'BOMBA DE AGUA',
            'RADIADOR', 'TERMOSTATO',
        ]
    },
}

# ── BUSCAR ARTICULOS POR GRUPO ──────────────────────
resumen_grupos = []

for num_grupo, info in grupos_criticos.items():
    print(f"\n{'='*75}")
    print(f"  {info['nombre']}")
    print(f"  {info['descripcion']}")
    print(f"{'='*75}")

    articulos_grupo = []

    for keyword in info['keywords']:
        coincidencias = df_articulos[
            (df_articulos['Nombre'].str.upper().str.contains(keyword, na=False)) &
            (df_articulos['Precio venta'] > 0) &
            (df_articulos['%Utilidad'] >= 20) &
            (df_articulos['Estado'] == 'Activo')
        ].copy()
        coincidencias['keyword'] = keyword
        articulos_grupo.append(coincidencias)

    if not articulos_grupo:
        print(f"  Sin articulos encontrados en catalogo")
        continue

    df_grupo = pd.concat(articulos_grupo).drop_duplicates(subset='Código')
    df_grupo = df_grupo.sort_values('%Utilidad', ascending=False)

    total_grupo    = len(df_grupo)
    agotados_grupo = len(df_grupo[df_grupo['Inventario'] == 0])
    margen_prom    = df_grupo['%Utilidad'].mean()
    inversion_min  = df_grupo['Costo neto'].sum()

    print(f"\n  Articulos encontrados en catalogo:  {total_grupo:>6,}")
    print(f"  Actualmente agotados:               {agotados_grupo:>6,}")
    print(f"  Margen promedio del grupo:          {margen_prom:>6.1f}%")
    print(f"  Inversion minima (1 und c/u):       {inversion_min:>10,.0f}")

    # Top 15 articulos del grupo
    top15 = df_grupo.head(15)
    print(f"\n  TOP 15 ARTICULOS DEL GRUPO:")
    print(f"  {'Articulo':<52} {'Precio':>10} {'Margen':>8} {'Stock':>7}")
    print(f"  {'-'*82}")

    for _, row in top15.iterrows():
        nombre = str(row['Nombre'])[:50]
        stock_txt = 'AGOTADO' if row['Inventario'] == 0 else str(int(row['Inventario']))
        print(f"  {nombre:<52} "
              f"  {row['Precio venta']:>8,.0f} "
              f"  {row['%Utilidad']:>6.1f}% "
              f"  {stock_txt:>7}")

    resumen_grupos.append({
        'Grupo'         : info['nombre'],
        'Total articulos': total_grupo,
        'Agotados'      : agotados_grupo,
        'Margen prom'   : round(margen_prom, 1),
        'Inversion min' : round(inversion_min, 0),
    })

ANALISIS 3 — ARTICULOS CRITICOS DE EMERGENCIA
Total Automotriz La Victoria
===========================================================================

===========================================================================
  GRUPO 1 — EL VEHICULO NO ARRANCA
  El cliente no puede moverse. Necesita solucion inmediata.
===========================================================================

  Articulos encontrados en catalogo:     514
  Actualmente agotados:                  354
  Margen promedio del grupo:            88.1%
  Inversion minima (1 und c/u):        5,955,595

  TOP 15 ARTICULOS DEL GRUPO:
  Articulo                                                 Precio   Margen   Stock
  ----------------------------------------------------------------------------------
  BOBINA NISSAN                                            35,700   3059.3%   AGOTADO
  ALTERNADOR HY TUCSON 05-                                115,000   1490.2%   AGOTADO
  CABLE BUJIAS TY HILUX 3VZE/RUNNER 92- 6CILINDROS         21,800    502.9%   AGOTADO
  CABLE BUJIAS TY RUNNER V6 3,0                            19,000    460.5%   AGOTADO
  CABLE BUJIAS HY ELANTRA NGK DOCH                         30,000    431.0%         1
  RELAY LUCES SPARK 98-13 VERSA                             8,500    403.0%         1
  CABLE BUJIAS MB MONTERO 6G74 V6                          27,000    377.9%   AGOTADO
  FAJA 6PK2110 ALTERNADOR                                   8,000    372.0%   AGOTADO
  FUSIBLE HEMBRA MEDIANO TODO AMPERAJE                      1,500    342.5%   AGOTADO
  TAPA DE DISTRIBUIDOR YD109A 4K, 5K // STARLET 82-         5,500    334.6%         1
  CABLE BUJIAS HY ELANTRA 1.6 /2.0 DOHG ECLIPSE/MIRA       23,000    307.1%         2
  JUEGO CARBON ALTERNADOR (FAX-149) AJ072                   2,000    300.4%         2
  FUSIBLE DE VIDRIO 15 AMP (DG3415)                            83    278.2%   AGOTADO
  FAJA 6PK1310 ALTERNADOR                                   6,000    254.0%   AGOTADO
  JUEGO CARBON ALTERNADOR TOYOTA FAX150 5X8 AJ076           2,000    254.0%         2

===========================================================================
  GRUPO 2 — EL VEHICULO NO FRENA
  Riesgo de seguridad inmediato. No puede circular.
===========================================================================

  Articulos encontrados en catalogo:     487
  Actualmente agotados:                  348
  Margen promedio del grupo:            80.6%
  Inversion minima (1 und c/u):        4,533,358

  TOP 15 ARTICULOS DEL GRUPO:
  Articulo                                                 Precio   Margen   Stock
  ----------------------------------------------------------------------------------
  PASTILLA DEL KIA SPECTRA 02-                             23,800   2006.2%   AGOTADO
  ZAPATA TRAS KIA SPECTRA 02-                              14,800   1209.7%   AGOTADO
  PASTILLA DE FRENO TRASERO FORD F150                      37,500    360.9%   AGOTADO
  PASTILLA DE FRENO CERAMICA TRAS MIT MONTERO 92-00        14,000    299.7%         1
  PASTILLA DE FRENO   NISSAN ALMERA                        18,000    298.2%         1
  PASTILLA DE FRENO DELANTERA CHEVROLET AVALANCHE 20       31,000    278.1%   AGOTADO
  Pastillas Freno - SWIFT RS413GL/RS413GA/RS415GL  D       20,000    260.6%   AGOTADO
  PASTILLA FLASHER ELECTRONICO 2PTS 24V UNIVERSAL           2,500    239.8%         1
  PASTILLA DE FRENO CERAMICA   HY TUCSON /KIA SPORTA       24,500    237.1%         1
  PASTILLA FRENO  SUBARU LEGACY 00-09 FORESTE 98-03        15,000    218.7%   AGOTADO
  PASTILLA FRENO TRASERA CHEVROLET AVALANCHE 2007          25,000    199.8%   AGOTADO
  PASTILLA DE FRENO CERAMICA  HY STAREX 97-07 IGUAL        18,500    198.4%         1
  DISCO DE FRENO DELANTERO VENTILADO VITARA 16-19          43,737    185.5%   AGOTADO
  PASTILLA FRENO  KIA/MAZDA 323/FOR                        12,900    185.4%   AGOTADO
  PASTILLA DE FRENO DAIHATSU CHARADE 88-92                  9,500    180.2%   AGOTADO

===========================================================================
  GRUPO 3 — EL VEHICULO NO TRANSMITE POTENCIA
  El vehiculo avanza mal o no avanza. No es util para el cliente.
===========================================================================

  Articulos encontrados en catalogo:     816
  Actualmente agotados:                  552
  Margen promedio del grupo:           297.8%
  Inversion minima (1 und c/u):       10,734,687

  TOP 15 ARTICULOS DEL GRUPO:
  Articulo                                                 Precio   Margen   Stock
  ----------------------------------------------------------------------------------
  MANILLA INTERNA LH COROLLA 03-08 HILUX HIACE TACOM        4,500   180667.2%         1
  ROLL RUEDA DELANTERA  29749                               7,000   1964.9%         1
  ROLL DE EMPUJE ISUZU NKR 2.8 JMC                         14,800   1209.7%   AGOTADO
  ABANICO TY COROLLA 7AF                                   96,300    933.9%   AGOTADO
  ROLL TENSOR HY TUCSON 2.5 V6 GASOLINA                    25,800    470.8%         1
  RETENEDOR MIDE 35X56X8.9X16.4 DIFERENCIAL TRASERO         9,000    431.0%   AGOTADO
  SEGURO SINCRONIZADOR                                      8,000    428.7%   AGOTADO
  Cobertores Buji - COROLLA K/2K/3K/3KH/4K (70/81)          4,500    296.2%         4
  EMPAQUE MANIFOOL COROLLA 4AF (87/91), COROLLA 5AF         3,000    293.3%   AGOTADO
  ROTULA SB2142 SUSPENCION TY COROLLA KE20 -74 TOYOT       14,500    285.6%         2
  ROTULA DE CREMALLERA TY/COROLLA EA86 HIDRAULICA          13,000    283.5%   AGOTADO
  CERRADURA CAJUELA TY COROLLA 2006 V/A                    20,000    278.2%   AGOTADO
  BOCINA TRASERA TY COROLLA 00'                            45,000    257.0%   AGOTADO
  ROLL DAC 45844042 DELANT  HONDA CRV 4WD                  19,800    252.5%         2
  ROLL TENSOR CHEVROLET SPART 800/1000                     13,500    238.4%        -1

===========================================================================
  GRUPO 4 — EL VEHICULO PIERDE FLUIDOS
  Si no se atiende a tiempo puede generar daño mayor al motor.
===========================================================================

  Articulos encontrados en catalogo:     775
  Actualmente agotados:                  466
  Margen promedio del grupo:           106.3%
  Inversion minima (1 und c/u):        6,545,249

  TOP 15 ARTICULOS DEL GRUPO:
  Articulo                                                 Precio   Margen   Stock
  ----------------------------------------------------------------------------------
  RETENEDOR HIDRAULICO 16X40X8                             80,000   3439.8%         1
  MARIPOSA RADIADOR                                           500   2358.2%         3
  RETENEDOR MIDE 105X135X9                                 12,000   2023.9%         1
  BOMBA DE AGUA 22R HILUX/CELICA 84-                       23,500   1979.7%         1
  RETENEDOR HIDRAULICO 17X40X8                              7,000   1138.9%         3
  Retenedor Cigueñal (41x56x8) J35 V6 HD Pilot             11,322    518.5%   AGOTADO
  EMPAQUE TAPA VALVULA TUCSON DIESEL 10-15 CENTRAL          6,000    506.1%         1
  EMPAQUE TAPA VALVULA - HILUX VIGO 2KD-FTV (05/-),         6,500    450.4%   AGOTADO
  RETENEDOR MIDE 35X56X8.9X16.4 DIFERENCIAL TRASERO         9,000    431.0%   AGOTADO
  RETENEDOR MIDE 88X106X8.7                                 8,800    419.2%   AGOTADO
  Retenedor Arbol Levas (39x53x8) J35 Ex ExL Lx Rtl         9,040    402.8%   AGOTADO
  EMPAQUE TAPA VALVULA TUCSON SANTA SORENTO DIESEL 2        9,000    352.3%         1
  EMPAQUE TAPA VALVULA 2H - JN-536 LAND CRUISER            14,645    350.0%   AGOTADO
  RETENEDOR CIGUANAL DELANTERO  HY ACCENT 2011- G4FC        3,700    347.1%   AGOTADO
  RETENEDOR MIDE 35X50X11 - 32136-U0100  NCP/  JAPON        7,500    342.5%   AGOTADO

In [39]:
# ═════════════════════ RESUMEN EJECUTIVO GRUPOS CRITICOS
# Vision consolidada de los 4 grupos
# ══════════════════════════════════════════════════

print("RESUMEN EJECUTIVO — ARTICULOS CRITICOS DE EMERGENCIA")
print("=" * 70)

df_resumen = pd.DataFrame(resumen_grupos)

print(f"\n{'Grupo':<45} {'Articulos':>9} {'Agotados':>9} "
      f"{'Margen':>8} {'Inversion min':>14}")
print(f"  {'-'*88}")

total_inversion = 0
for _, row in df_resumen.iterrows():
    grupo_corto = str(row['Grupo'])[:43]
    print(f"  {grupo_corto:<45} "
          f"{int(row['Total articulos']):>9,} "
          f"{int(row['Agotados']):>9,} "
          f"{row['Margen prom']:>7.1f}% "
          f"  {row['Inversion min']:>12,.0f}")
    total_inversion += row['Inversion min']

print(f"\n  {'TOTAL INVERSION MINIMA (1 und x articulo)':<45} "
      f"  {total_inversion:>12,.0f}")
print(f"  {'TOTAL INVERSION RECOMENDADA (2 und x articulo)':<45} "
      f"  {total_inversion*2:>12,.0f}")

print(f"\n\nREGLA DE ORO PARA LA VICTORIA:")
print(f"  Estos articulos NUNCA pueden estar en cero.")
print(f"  Cuando llegue al ultimo en stock, se pide de inmediato.")
print(f"  El costo de perder una venta critica no es solo esa venta —")
print(f"  es perder al cliente para siempre.")

RESUMEN EJECUTIVO — ARTICULOS CRITICOS DE EMERGENCIA
======================================================================

Grupo                                         Articulos  Agotados   Margen  Inversion min
  ----------------------------------------------------------------------------------------
  GRUPO 1 — EL VEHICULO NO ARRANCA                    514       354    88.1%      5,955,595
  GRUPO 2 — EL VEHICULO NO FRENA                      487       348    80.6%      4,533,358
  GRUPO 3 — EL VEHICULO NO TRANSMITE POTENCIA         816       552   297.8%     10,734,687
  GRUPO 4 — EL VEHICULO PIERDE FLUIDOS                775       466   106.3%      6,545,249

  TOTAL INVERSION MINIMA (1 und x articulo)         27,768,889
  TOTAL INVERSION RECOMENDADA (2 und x articulo)     55,537,778


REGLA DE ORO PARA LA VICTORIA:
  Estos articulos NUNCA pueden estar en cero.
  Cuando llegue al ultimo en stock, se pide de inmediato.
  El costo de perder una venta critica no es solo esa venta —
  es perder al cliente para siempre.

 — Analisis de meta salarial

In [43]:
# ══════════════════════════════════════════════════
# CELDA 24 — ESCALERA SALARIAL PROGRESIVA
# Escalones iguales para Charlie y Rosa
# Escalon 1: ₡100,000 semanales c/u
# Escalon 2: ₡125,000 semanales c/u
# Escalon 3: ₡150,000 semanales c/u
# Escalon 4: ₡175,000 semanales c/u
# Escalon 5: ₡200,000 semanales c/u
# ══════════════════════════════════════════════════

print("ESCALERA SALARIAL PROGRESIVA — TOTAL AUTOMOTRIZ LA VICTORIA")
print("Charlie Marenco y Rosa — Mismo salario por escalon")
print("=" * 70)

margen           = 0.35
semanas_mes      = 4
dias_habiles_mes = 23
ticket_promedio  = 11080
promedio_ref     = 7888601  # promedio mensual Rio Frio

# ── GASTOS OPERATIVOS FIJOS ──────────────────────────
gastos_fijos = {
    'Alquiler'               : 226000,
    'Basura'                 : 3000,
    'Luz'                    : 20000,
    'Agua'                   : 6000,
    'Internet'               : 18000,
    'Sistema'                : 22600,
    'Contabilidad'           : 25000,
    'Inteligencia Artificial': 7000,
    'Linea Telefonica'       : 15000,
    'Seguro Rosa'            : 50000,
    'Seguro Charlie'         : 50000,
    'Poliza'                 : 5000,
}

total_operativo = sum(gastos_fijos.values())

print(f"\nGASTOS OPERATIVOS FIJOS (sin salarios): {total_operativo:>12,.0f}")
print(f"Margen de utilidad aplicado:            {margen*100:>11.0f}%")
print(f"Ticket promedio de referencia:          {ticket_promedio:>12,.0f}")
print(f"Promedio mensual negocio Rio Frio:      {promedio_ref:>12,.0f}")

# ── ESCALONES SALARIALES ────────────────────────────
escalones = [
    {'escalon': 1, 'semanal': 100000, 'fase': 'Arranque'},
    {'escalon': 2, 'semanal': 125000, 'fase': 'Estabilizacion'},
    {'escalon': 3, 'semanal': 150000, 'fase': 'Crecimiento'},
    {'escalon': 4, 'semanal': 175000, 'fase': 'Consolidacion'},
    {'escalon': 5, 'semanal': 200000, 'fase': 'Meta final'},
]

print(f"\n\n{'ESC':<5} {'FASE':<18} {'Semanal c/u':>12} {'Salarios/mes':>13} "
      f"{'Total cubrir':>13} {'Ventas min':>13} {'Facts/dia':>10} {'Venta/dia':>12}")
print(f"  {'-'*100}")

tabla_escalones = []

for esc in escalones:
    semanal         = esc['semanal']
    salario_mensual = semanal * semanas_mes        # uno solo
    total_salarios  = salario_mensual * 2          # Charlie + Rosa
    total_necesario = total_operativo + total_salarios
    ventas_min      = total_necesario / margen
    facturas_dia    = (ventas_min / ticket_promedio) / dias_habiles_mes
    venta_dia       = ventas_min / dias_habiles_mes
    pct_vs_ref      = ventas_min / promedio_ref * 100

    tabla_escalones.append({
        'escalon'        : esc['escalon'],
        'fase'           : esc['fase'],
        'semanal'        : semanal,
        'total_salarios' : total_salarios,
        'total_necesario': total_necesario,
        'ventas_min'     : ventas_min,
        'facturas_dia'   : facturas_dia,
        'venta_dia'      : venta_dia,
        'pct_vs_ref'     : pct_vs_ref,
    })

    print(f"  {esc['escalon']:<5} {esc['fase']:<18} "
          f"  {semanal:>10,.0f} "
          f"  {total_salarios:>11,.0f} "
          f"  {total_necesario:>11,.0f} "
          f"  {ventas_min:>11,.0f} "
          f"  {facturas_dia:>9.1f} "
          f"  {venta_dia:>10,.0f}")

# ── DETALLE POR ESCALON ──────────────────────────────
print(f"\n\nDETALLE POR ESCALON:")

for e in tabla_escalones:
    print(f"\n{'='*70}")
    print(f"  ESCALON {e['escalon']} — {e['fase'].upper()}")
    print(f"  Salario: {e['semanal']:,.0f} semanales c/u "
          f"({e['semanal']*semanas_mes:,.0f} mensuales c/u)")
    print(f"{'='*70}")
    print(f"  Salarios totales (Charlie + Rosa):  {e['total_salarios']:>12,.0f}")
    print(f"  Gastos operativos:                  {total_operativo:>12,.0f}")
    print(f"  {'─'*48}")
    print(f"  TOTAL A CUBRIR POR MES:             {e['total_necesario']:>12,.0f}")
    print(f"  VENTAS MINIMAS NECESARIAS:          {e['ventas_min']:>12,.0f}")
    print(f"  {'─'*48}")
    print(f"  Venta minima diaria:                {e['venta_dia']:>12,.0f}")
    print(f"  Facturas diarias necesarias:        {e['facturas_dia']:>12.1f}")
    print(f"  Porcentaje vs Rio Frio:             {e['pct_vs_ref']:>11.1f}%")

    # Margen de seguridad vs Rio Frio
    margen_seguridad = promedio_ref - e['ventas_min']
    print(f"  Margen de seguridad vs Rio Frio:    {margen_seguridad:>12,.0f}")

# ── RESUMEN DE PROGRESION ────────────────────────────
print(f"\n\n{'='*70}")
print(f"  RESUMEN — PROGRESION SALARIAL")
print(f"{'='*70}")
print(f"\n  {'Escalon':<5} {'Fase':<18} {'Ventas min/mes':>15} "
      f"{'Facts/dia':>10} {'% vs Rio Frio':>14}")
print(f"  {'-'*65}")

for e in tabla_escalones:
    print(f"  {e['escalon']:<5} {e['fase']:<18} "
          f"  {e['ventas_min']:>13,.0f} "
          f"  {e['facturas_dia']:>9.1f} "
          f"  {e['pct_vs_ref']:>12.1f}%")

incremento_e1_e5 = tabla_escalones[-1]['ventas_min'] - tabla_escalones[0]['ventas_min']
incremento_facts = tabla_escalones[-1]['facturas_dia'] - tabla_escalones[0]['facturas_dia']

print(f"\n  Diferencia entre Escalon 1 y Escalon 5:")
print(f"  Ventas adicionales necesarias:      {incremento_e1_e5:>12,.0f}")
print(f"  Facturas adicionales por dia:       {incremento_facts:>12.1f}")

print(f"\n  CONCLUSION:")
print(f"  Pasar del Escalon 1 al Escalon 5 requiere")
print(f"  aproximadamente {incremento_facts:.1f} facturas adicionales por dia.")
print(f"  Con el ticket promedio de {ticket_promedio:,.0f} por factura,")
print(f"  la diferencia entre ganar {tabla_escalones[0]['semanal']:,.0f}")
print(f"  y ganar {tabla_escalones[-1]['semanal']:,.0f} semanales es operativamente")
print(f"  muy manejable si el volumen de clientes crece")
print(f"  de forma sostenida desde el primer mes.")

ESCALERA SALARIAL PROGRESIVA — TOTAL AUTOMOTRIZ LA VICTORIA
Charlie Marenco y Rosa — Mismo salario por escalon
======================================================================

GASTOS OPERATIVOS FIJOS (sin salarios):      447,600
Margen de utilidad aplicado:                     35%
Ticket promedio de referencia:                11,080
Promedio mensual negocio Rio Frio:         7,888,601


ESC   FASE                Semanal c/u  Salarios/mes  Total cubrir    Ventas min  Facts/dia    Venta/dia
  ----------------------------------------------------------------------------------------------------
  1     Arranque                100,000       800,000     1,247,600     3,564,571        14.0      154,981
  2     Estabilizacion          125,000     1,000,000     1,447,600     4,136,000        16.2      179,826
  3     Crecimiento             150,000     1,200,000     1,647,600     4,707,429        18.5      204,671
  4     Consolidacion           175,000     1,400,000     1,847,600     5,278,857        20.7      229,516
  5     Meta final              200,000     1,600,000     2,047,600     5,850,286        23.0      254,360


DETALLE POR ESCALON:

======================================================================
  ESCALON 1 — ARRANQUE
  Salario: 100,000 semanales c/u (400,000 mensuales c/u)
======================================================================
  Salarios totales (Charlie + Rosa):       800,000
  Gastos operativos:                       447,600
  ────────────────────────────────────────────────
  TOTAL A CUBRIR POR MES:                1,247,600
  VENTAS MINIMAS NECESARIAS:             3,564,571
  ────────────────────────────────────────────────
  Venta minima diaria:                     154,981
  Facturas diarias necesarias:                14.0
  Porcentaje vs Rio Frio:                    45.2%
  Margen de seguridad vs Rio Frio:       4,324,030

======================================================================
  ESCALON 2 — ESTABILIZACION
  Salario: 125,000 semanales c/u (500,000 mensuales c/u)
======================================================================
  Salarios totales (Charlie + Rosa):     1,000,000
  Gastos operativos:                       447,600
  ────────────────────────────────────────────────
  TOTAL A CUBRIR POR MES:                1,447,600
  VENTAS MINIMAS NECESARIAS:             4,136,000
  ────────────────────────────────────────────────
  Venta minima diaria:                     179,826
  Facturas diarias necesarias:                16.2
  Porcentaje vs Rio Frio:                    52.4%
  Margen de seguridad vs Rio Frio:       3,752,601

======================================================================
  ESCALON 3 — CRECIMIENTO
  Salario: 150,000 semanales c/u (600,000 mensuales c/u)
======================================================================
  Salarios totales (Charlie + Rosa):     1,200,000
  Gastos operativos:                       447,600
  ────────────────────────────────────────────────
  TOTAL A CUBRIR POR MES:                1,647,600
  VENTAS MINIMAS NECESARIAS:             4,707,429
  ────────────────────────────────────────────────
  Venta minima diaria:                     204,671
  Facturas diarias necesarias:                18.5
  Porcentaje vs Rio Frio:                    59.7%
  Margen de seguridad vs Rio Frio:       3,181,172

======================================================================
  ESCALON 4 — CONSOLIDACION
  Salario: 175,000 semanales c/u (700,000 mensuales c/u)
======================================================================
  Salarios totales (Charlie + Rosa):     1,400,000
  Gastos operativos:                       447,600
  ────────────────────────────────────────────────
  TOTAL A CUBRIR POR MES:                1,847,600
  VENTAS MINIMAS NECESARIAS:             5,278,857
  ────────────────────────────────────────────────
  Venta minima diaria:                     229,516
  Facturas diarias necesarias:                20.7
  Porcentaje vs Rio Frio:                    66.9%
  Margen de seguridad vs Rio Frio:       2,609,744

======================================================================
  ESCALON 5 — META FINAL
  Salario: 200,000 semanales c/u (800,000 mensuales c/u)
======================================================================
  Salarios totales (Charlie + Rosa):     1,600,000
  Gastos operativos:                       447,600
  ────────────────────────────────────────────────
  TOTAL A CUBRIR POR MES:                2,047,600
  VENTAS MINIMAS NECESARIAS:             5,850,286
  ────────────────────────────────────────────────
  Venta minima diaria:                     254,360
  Facturas diarias necesarias:                23.0
  Porcentaje vs Rio Frio:                    74.2%
  Margen de seguridad vs Rio Frio:       2,038,315


======================================================================
  RESUMEN — PROGRESION SALARIAL
======================================================================

  Escalon Fase                Ventas min/mes  Facts/dia  % vs Rio Frio
  -----------------------------------------------------------------
  1     Arranque                 3,564,571        14.0           45.2%
  2     Estabilizacion           4,136,000        16.2           52.4%
  3     Crecimiento              4,707,429        18.5           59.7%
  4     Consolidacion            5,278,857        20.7           66.9%
  5     Meta final               5,850,286        23.0           74.2%

  Diferencia entre Escalon 1 y Escalon 5:
  Ventas adicionales necesarias:         2,285,714
  Facturas adicionales por dia:                9.0

  CONCLUSION:
  Pasar del Escalon 1 al Escalon 5 requiere
  aproximadamente 9.0 facturas adicionales por dia.
  Con el ticket promedio de 11,080 por factura,
  la diferencia entre ganar 100,000
  y ganar 200,000 semanales es operativamente
  muy manejable si el volumen de clientes crece
  de forma sostenida desde el primer mes.

In [44]:
# ═════════ CLIENTES FRECUENTES
# Identificar quienes compraron mas veces,
# cuanto gastaron y cuando fue su ultima compra.
# Estos son los clientes que La Victoria
# debe contactar desde el primer dia.
# ══════════════════════════════════════════════════

print("ANALISIS DE CLIENTES FRECUENTES")
print("Negocio de referencia — Rio Frio")
print("=" * 70)

# Excluir registros sin nombre de cliente
df_clientes_fact = df_facturas[
    ~df_facturas['cliente'].isin(['NAN', 'NONE', ''])
].copy()

# Agrupar por cliente
resumen_clientes = df_clientes_fact.groupby('cliente').agg(
    total_compras    = ('total', 'count'),
    gasto_total      = ('total', 'sum'),
    ticket_promedio  = ('total', 'mean'),
    primera_compra   = ('fecha', 'min'),
    ultima_compra    = ('fecha', 'max'),
    gasto_maximo     = ('total', 'max'),
).reset_index()

# Calcular dias desde ultima compra
fecha_corte = df_facturas['fecha'].max()
resumen_clientes['dias_sin_comprar'] = (
    fecha_corte - resumen_clientes['ultima_compra']
).dt.days

# Calcular frecuencia promedio en dias entre compras
resumen_clientes['rango_dias'] = (
    resumen_clientes['ultima_compra'] - resumen_clientes['primera_compra']
).dt.days

resumen_clientes['frecuencia_dias'] = (
    resumen_clientes['rango_dias'] / resumen_clientes['total_compras']
).round(0)

# Clasificar clientes por valor
def clasificar_cliente(row):
    if row['total_compras'] >= 20 and row['gasto_total'] >= 100000:
        return 'A — VIP'
    elif row['total_compras'] >= 10 and row['gasto_total'] >= 50000:
        return 'B — Frecuente'
    elif row['total_compras'] >= 5:
        return 'C — Regular'
    else:
        return 'D — Ocasional'

resumen_clientes['clasificacion'] = resumen_clientes.apply(
    clasificar_cliente, axis=1
)

# Ordenar por total de compras
resumen_clientes = resumen_clientes.sort_values(
    'total_compras', ascending=False
).reset_index(drop=True)

# Resumen por clasificacion
print(f"\nDISTRIBUCION DE CLIENTES POR CLASIFICACION:")
print(f"  {'Clasificacion':<20} {'Clientes':>9} {'% del total':>12}")
print(f"  {'-'*45}")
dist = resumen_clientes.groupby('clasificacion')['cliente'].count()
for clase, cantidad in dist.items():
    pct = cantidad / len(resumen_clientes) * 100
    print(f"  {clase:<20} {cantidad:>9,} {pct:>11.1f}%")

print(f"\n  Total clientes unicos: {len(resumen_clientes):,}")

# Top 30 clientes por frecuencia
print(f"\n\nTOP 30 CLIENTES MAS FRECUENTES:")
print(f"  {'#':<4} {'Cliente':<30} {'Compras':>8} {'Gasto Total':>13} "
      f"{'Ticket Prom':>12} {'Dias sin comprar':>17} {'Clase':>15}")
print(f"  {'-'*102}")

for i, row in resumen_clientes.head(30).iterrows():
    nombre = str(row['cliente'])[:28]
    print(f"  {i+1:<4} {nombre:<30} "
          f"{int(row['total_compras']):>8,} "
          f"  {row['gasto_total']:>11,.0f} "
          f"  {row['ticket_promedio']:>10,.0f} "
          f"  {int(row['dias_sin_comprar']):>15,} "
          f"  {row['clasificacion']:>15}")

# Clientes VIP detalle
clientes_vip = resumen_clientes[
    resumen_clientes['clasificacion'] == 'A — VIP'
]
print(f"\n\nCLIENTES VIP — DETALLE COMPLETO:")
print(f"  Estos son los clientes que La Victoria")
print(f"  debe priorizar desde el primer dia de apertura.")
print(f"  {'─'*65}")

for i, row in clientes_vip.iterrows():
    nombre = str(row['cliente'])[:35]
    print(f"\n  {nombre}")
    print(f"  Compras realizadas:      {int(row['total_compras']):>8,}")
    print(f"  Gasto total historico:   {row['gasto_total']:>10,.0f}")
    print(f"  Ticket promedio:         {row['ticket_promedio']:>10,.0f}")
    print(f"  Gasto maximo en una vez: {row['gasto_maximo']:>10,.0f}")
    print(f"  Primera compra:          "
          f"{row['primera_compra'].strftime('%d/%m/%Y'):>12}")
    print(f"  Ultima compra:           "
          f"{row['ultima_compra'].strftime('%d/%m/%Y'):>12}")
    print(f"  Dias sin comprar:        {int(row['dias_sin_comprar']):>8,}")
    print(f"  Frecuencia promedio:     cada {int(row['frecuencia_dias'])} dias")

ANALISIS DE CLIENTES FRECUENTES
Negocio de referencia — Rio Frio
======================================================================

DISTRIBUCION DE CLIENTES POR CLASIFICACION:
  Clasificacion         Clientes  % del total
  ---------------------------------------------
  A — VIP                    151         3.0%
  B — Frecuente              160         3.2%
  C — Regular                322         6.4%
  D — Ocasional            4,399        87.4%

  Total clientes unicos: 5,032


TOP 30 CLIENTES MAS FRECUENTES:
  #    Cliente                         Compras   Gasto Total  Ticket Prom  Dias sin comprar           Clase
  ------------------------------------------------------------------------------------------------------
  1    CHINDO                              308     1,810,068        5,877                 3           A — VIP
  2    JOSE                                198     1,675,079        8,460                 0           A — VIP
  3    MULTISERVICIOS COGO DE SARAP        189     2,382,951       12,608                23           A — VIP
  4    LUIS GERARDO ALFARO MORA            138       453,206        3,284                10           A — VIP
  5    CARLOS                              122       954,988        7,828                 3           A — VIP
  6    CONTADO                             117       374,656        3,202                 4           A — VIP
  7    LUIS                                117       789,610        6,749                 7           A — VIP
  8    GERARDO                             109     1,002,785        9,200                11           A — VIP
  9    ERICK                               102       716,352        7,023                10           A — VIP
  10   MARIO                                96       809,865        8,436                 8           A — VIP
  11   CLIENTE                              91       532,452        5,851                12           A — VIP
  12   SERLEY ELIECER PEREZ ROSALES         91       925,847       10,174                 8           A — VIP
  13   DAVID                                88       612,332        6,958                 2           A — VIP
  14   ANTHONY STIVEN VALVERDE GARC         87       916,408       10,533                10           A — VIP
  15   OSCAR                                86       422,942        4,918                 0           A — VIP
  16   LUIS GEOVANNY ENRIQUEZ CORDE         86     2,074,459       24,122                 9           A — VIP
  17   KENNER JOSUE RIOS SOLIS              78     1,441,570       18,482                 1           A — VIP
  18   1                                    76       264,725        3,483                 2           A — VIP
  19   DANIEL                               74       545,425        7,371                 5           A — VIP
  20   ORLANDO QUIROS                       74       490,136        6,623                 9           A — VIP
  21   MAYRA LISSET MEMBREÑO COREA          74       827,080       11,177                 0           A — VIP
  22   MARCOS                               66       406,626        6,161                11           A — VIP
  23   VICTOR                               66       481,205        7,291                12           A — VIP
  24   NIXON ALBERTO BRICEÑO SALAS          60       659,384       10,990                 4           A — VIP
  25   ALEXANDER                            59       577,997        9,797                 3           A — VIP
  26   DIEGO                                59       312,977        5,305                23           A — VIP
  27   ROY FRANCISCO PORRAS MASIS           58       563,046        9,708                 4           A — VIP
  28   JUAN                                 56       539,058        9,626                 9           A — VIP
  29   TALLER QUIROS                        56       431,163        7,699                 8           A — VIP
  30   EMANUEL COTO CAMBRONERO              55       511,777        9,305                87           A — VIP


CLIENTES VIP — DETALLE COMPLETO:
  Estos son los clientes que La Victoria
  debe priorizar desde el primer dia de apertura.
  ─────────────────────────────────────────────────────────────────

  CHINDO
  Compras realizadas:           308
  Gasto total historico:    1,810,068
  Ticket promedio:              5,877
  Gasto maximo en una vez:     20,790
  Primera compra:            20/09/2023
  Ultima compra:             17/09/2025
  Dias sin comprar:               3
  Frecuencia promedio:     cada 2 dias

  JOSE
  Compras realizadas:           198
  Gasto total historico:    1,675,079
  Ticket promedio:              8,460
  Gasto maximo en una vez:    237,960
  Primera compra:            27/09/2023
  Ultima compra:             20/09/2025
  Dias sin comprar:               0
  Frecuencia promedio:     cada 4 dias

  MULTISERVICIOS COGO DE SARAPIQUI SO
  Compras realizadas:           189
  Gasto total historico:    2,382,951
  Ticket promedio:             12,608
  Gasto maximo en una vez:    167,296
  Primera compra:            27/09/2023
  Ultima compra:             28/08/2025
  Dias sin comprar:              23
  Frecuencia promedio:     cada 4 dias

  LUIS GERARDO ALFARO MORA
  Compras realizadas:           138
  Gasto total historico:      453,206
  Ticket promedio:              3,284
  Gasto maximo en una vez:     52,065
  Primera compra:            10/11/2023
  Ultima compra:             10/09/2025
  Dias sin comprar:              10
  Frecuencia promedio:     cada 5 dias

  CARLOS
  Compras realizadas:           122
  Gasto total historico:      954,988
  Ticket promedio:              7,828
  Gasto maximo en una vez:     75,000
  Primera compra:            23/09/2023
  Ultima compra:             17/09/2025
  Dias sin comprar:               3
  Frecuencia promedio:     cada 6 dias

  CONTADO
  Compras realizadas:           117
  Gasto total historico:      374,656
  Ticket promedio:              3,202
  Gasto maximo en una vez:     20,050
  Primera compra:            30/09/2023
  Ultima compra:             16/09/2025
  Dias sin comprar:               4
  Frecuencia promedio:     cada 6 dias

  LUIS
  Compras realizadas:           117
  Gasto total historico:      789,610
  Ticket promedio:              6,749
  Gasto maximo en una vez:     81,400
  Primera compra:            20/09/2023
  Ultima compra:             13/09/2025
  Dias sin comprar:               7
  Frecuencia promedio:     cada 6 dias

  GERARDO
  Compras realizadas:           109
  Gasto total historico:    1,002,785
  Ticket promedio:              9,200
  Gasto maximo en una vez:     69,500
  Primera compra:            28/09/2023
  Ultima compra:             09/09/2025
  Dias sin comprar:              11
  Frecuencia promedio:     cada 7 dias

  ERICK
  Compras realizadas:           102
  Gasto total historico:      716,352
  Ticket promedio:              7,023
  Gasto maximo en una vez:     46,800
  Primera compra:            12/10/2023
  Ultima compra:             10/09/2025
  Dias sin comprar:              10
  Frecuencia promedio:     cada 7 dias

  MARIO
  Compras realizadas:            96
  Gasto total historico:      809,865
  Ticket promedio:              8,436
  Gasto maximo en una vez:     78,381
  Primera compra:            22/09/2023
  Ultima compra:             12/09/2025
  Dias sin comprar:               8
  Frecuencia promedio:     cada 8 dias

  CLIENTE
  Compras realizadas:            91
  Gasto total historico:      532,452
  Ticket promedio:              5,851
  Gasto maximo en una vez:     77,900
  Primera compra:            21/12/2023
  Ultima compra:             08/09/2025
  Dias sin comprar:              12
  Frecuencia promedio:     cada 7 dias

  SERLEY ELIECER PEREZ ROSALES
  Compras realizadas:            91
  Gasto total historico:      925,847
  Ticket promedio:             10,174
  Gasto maximo en una vez:     82,657
  Primera compra:            26/09/2023
  Ultima compra:             12/09/2025
  Dias sin comprar:               8
  Frecuencia promedio:     cada 8 dias

  DAVID
  Compras realizadas:            88
  Gasto total historico:      612,332
  Ticket promedio:              6,958
  Gasto maximo en una vez:     43,000
  Primera compra:            29/09/2023
  Ultima compra:             18/09/2025
  Dias sin comprar:               2
  Frecuencia promedio:     cada 8 dias

  ANTHONY STIVEN VALVERDE GARCIA
  Compras realizadas:            87
  Gasto total historico:      916,408
  Ticket promedio:             10,533
  Gasto maximo en una vez:     44,000
  Primera compra:            07/08/2024
  Ultima compra:             10/09/2025
  Dias sin comprar:              10
  Frecuencia promedio:     cada 5 dias

  OSCAR
  Compras realizadas:            86
  Gasto total historico:      422,942
  Ticket promedio:              4,918
  Gasto maximo en una vez:     59,000
  Primera compra:            02/10/2023
  Ultima compra:             20/09/2025
  Dias sin comprar:               0
  Frecuencia promedio:     cada 8 dias

  LUIS GEOVANNY ENRIQUEZ CORDERO
  Compras realizadas:            86
  Gasto total historico:    2,074,459
  Ticket promedio:             24,122
  Gasto maximo en una vez:    215,000
  Primera compra:            20/09/2023
  Ultima compra:             11/09/2025
  Dias sin comprar:               9
  Frecuencia promedio:     cada 8 dias

  KENNER JOSUE RIOS SOLIS
  Compras realizadas:            78
  Gasto total historico:    1,441,570
  Ticket promedio:             18,482
  Gasto maximo en una vez:    232,780
  Primera compra:            14/10/2023
  Ultima compra:             19/09/2025
  Dias sin comprar:               1
  Frecuencia promedio:     cada 9 dias

  1
  Compras realizadas:            76
  Gasto total historico:      264,725
  Ticket promedio:              3,483
  Gasto maximo en una vez:     17,700
  Primera compra:            16/10/2023
  Ultima compra:             18/09/2025
  Dias sin comprar:               2
  Frecuencia promedio:     cada 9 dias

  DANIEL
  Compras realizadas:            74
  Gasto total historico:      545,425
  Ticket promedio:              7,371
  Gasto maximo en una vez:     62,024
  Primera compra:            05/10/2023
  Ultima compra:             15/09/2025
  Dias sin comprar:               5
  Frecuencia promedio:     cada 10 dias

  ORLANDO QUIROS
  Compras realizadas:            74
  Gasto total historico:      490,136
  Ticket promedio:              6,623
  Gasto maximo en una vez:     22,500
  Primera compra:            30/09/2023
  Ultima compra:             11/09/2025
  Dias sin comprar:               9
  Frecuencia promedio:     cada 10 dias

  MAYRA LISSET MEMBREÑO COREA
  Compras realizadas:            74
  Gasto total historico:      827,080
  Ticket promedio:             11,177
  Gasto maximo en una vez:    196,000
  Primera compra:            21/09/2023
  Ultima compra:             20/09/2025
  Dias sin comprar:               0
  Frecuencia promedio:     cada 10 dias

  MARCOS
  Compras realizadas:            66
  Gasto total historico:      406,626
  Ticket promedio:              6,161
  Gasto maximo en una vez:     23,500
  Primera compra:            02/10/2023
  Ultima compra:             09/09/2025
  Dias sin comprar:              11
  Frecuencia promedio:     cada 11 dias

  VICTOR
  Compras realizadas:            66
  Gasto total historico:      481,205
  Ticket promedio:              7,291
  Gasto maximo en una vez:     39,000
  Primera compra:            07/10/2023
  Ultima compra:             08/09/2025
  Dias sin comprar:              12
  Frecuencia promedio:     cada 11 dias

  NIXON ALBERTO BRICEÑO SALAS
  Compras realizadas:            60
  Gasto total historico:      659,384
  Ticket promedio:             10,990
  Gasto maximo en una vez:     57,500
  Primera compra:            03/10/2023
  Ultima compra:             16/09/2025
  Dias sin comprar:               4
  Frecuencia promedio:     cada 12 dias

  ALEXANDER
  Compras realizadas:            59
  Gasto total historico:      577,997
  Ticket promedio:              9,797
  Gasto maximo en una vez:    100,010
  Primera compra:            23/09/2023
  Ultima compra:             17/09/2025
  Dias sin comprar:               3
  Frecuencia promedio:     cada 12 dias

  DIEGO
  Compras realizadas:            59
  Gasto total historico:      312,977
  Ticket promedio:              5,305
  Gasto maximo en una vez:     43,600
  Primera compra:            28/09/2023
  Ultima compra:             28/08/2025
  Dias sin comprar:              23
  Frecuencia promedio:     cada 12 dias

  ROY FRANCISCO PORRAS MASIS
  Compras realizadas:            58
  Gasto total historico:      563,046
  Ticket promedio:              9,708
  Gasto maximo en una vez:    124,376
  Primera compra:            20/09/2023
  Ultima compra:             16/09/2025
  Dias sin comprar:               4
  Frecuencia promedio:     cada 13 dias

  JUAN
  Compras realizadas:            56
  Gasto total historico:      539,058
  Ticket promedio:              9,626
  Gasto maximo en una vez:     95,000
  Primera compra:            18/10/2023
  Ultima compra:             11/09/2025
  Dias sin comprar:               9
  Frecuencia promedio:     cada 12 dias

  TALLER QUIROS
  Compras realizadas:            56
  Gasto total historico:      431,163
  Ticket promedio:              7,699
  Gasto maximo en una vez:     32,100
  Primera compra:            17/10/2023
  Ultima compra:             12/09/2025
  Dias sin comprar:               8
  Frecuencia promedio:     cada 12 dias

  EMANUEL COTO CAMBRONERO
  Compras realizadas:            55
  Gasto total historico:      511,777
  Ticket promedio:              9,305
  Gasto maximo en una vez:     53,980
  Primera compra:            26/01/2024
  Ultima compra:             25/06/2025
  Dias sin comprar:              87
  Frecuencia promedio:     cada 9 dias

  RAFA
  Compras realizadas:            53
  Gasto total historico:      444,432
  Ticket promedio:              8,386
  Gasto maximo en una vez:     40,000
  Primera compra:            28/09/2023
  Ultima compra:             15/09/2025
  Dias sin comprar:               5
  Frecuencia promedio:     cada 14 dias

  RICARDO
  Compras realizadas:            53
  Gasto total historico:      467,568
  Ticket promedio:              8,822
  Gasto maximo en una vez:     43,250
  Primera compra:            30/09/2023
  Ultima compra:             03/09/2025
  Dias sin comprar:              17
  Frecuencia promedio:     cada 13 dias

  CLIENTE CONTADO
  Compras realizadas:            52
  Gasto total historico:      177,698
  Ticket promedio:              3,417
  Gasto maximo en una vez:     36,600
  Primera compra:            09/10/2023
  Ultima compra:             20/09/2025
  Dias sin comprar:               0
  Frecuencia promedio:     cada 14 dias

  ANDRES
  Compras realizadas:            48
  Gasto total historico:      354,616
  Ticket promedio:              7,388
  Gasto maximo en una vez:     50,744
  Primera compra:            04/11/2023
  Ultima compra:             08/09/2025
  Dias sin comprar:              12
  Frecuencia promedio:     cada 14 dias

  ANDREY
  Compras realizadas:            48
  Gasto total historico:      376,235
  Ticket promedio:              7,838
  Gasto maximo en una vez:     56,180
  Primera compra:            11/01/2024
  Ultima compra:             20/09/2025
  Dias sin comprar:               0
  Frecuencia promedio:     cada 13 dias

  FRANCISCO
  Compras realizadas:            48
  Gasto total historico:      573,563
  Ticket promedio:             11,949
  Gasto maximo en una vez:    156,500
  Primera compra:            28/09/2023
  Ultima compra:             03/09/2025
  Dias sin comprar:              17
  Frecuencia promedio:     cada 15 dias

  JESSICA ANGULO CARPIO
  Compras realizadas:            47
  Gasto total historico:      725,666
  Ticket promedio:             15,440
  Gasto maximo en una vez:     91,043
  Primera compra:            07/03/2024
  Ultima compra:             12/09/2025
  Dias sin comprar:               8
  Frecuencia promedio:     cada 12 dias

  BEYLOR JOSE ESPINOZA VILLATORO
  Compras realizadas:            47
  Gasto total historico:      266,017
  Ticket promedio:              5,660
  Gasto maximo en una vez:     24,800
  Primera compra:            30/09/2023
  Ultima compra:             20/09/2025
  Dias sin comprar:               0
  Frecuencia promedio:     cada 15 dias

  VIVERO RIO FRIO SOCIEDAD ANONIMA
  Compras realizadas:            47
  Gasto total historico:    1,770,469
  Ticket promedio:             37,670
  Gasto maximo en una vez:    395,630
  Primera compra:            21/09/2023
  Ultima compra:             16/09/2025
  Dias sin comprar:               4
  Frecuencia promedio:     cada 15 dias

  MARVIN
  Compras realizadas:            45
  Gasto total historico:      340,497
  Ticket promedio:              7,567
  Gasto maximo en una vez:     65,000
  Primera compra:            11/11/2023
  Ultima compra:             15/09/2025
  Dias sin comprar:               5
  Frecuencia promedio:     cada 15 dias

  VALENTIN
  Compras realizadas:            45
  Gasto total historico:      263,853
  Ticket promedio:              5,863
  Gasto maximo en una vez:     25,000
  Primera compra:            18/11/2023
  Ultima compra:             20/09/2025
  Dias sin comprar:               0
  Frecuencia promedio:     cada 15 dias

  VICTOR ALEJANDRO PICADO VILLALOBOS
  Compras realizadas:            45
  Gasto total historico:      615,838
  Ticket promedio:             13,685
  Gasto maximo en una vez:     67,920
  Primera compra:            07/12/2023
  Ultima compra:             30/08/2025
  Dias sin comprar:              21
  Frecuencia promedio:     cada 14 dias

  MANUEL
  Compras realizadas:            45
  Gasto total historico:      333,571
  Ticket promedio:              7,413
  Gasto maximo en una vez:     35,280
  Primera compra:            22/09/2023
  Ultima compra:             18/09/2025
  Dias sin comprar:               2
  Frecuencia promedio:     cada 16 dias

  MARVIN RODRIGUEZ DURAN
  Compras realizadas:            45
  Gasto total historico:      800,071
  Ticket promedio:             17,779
  Gasto maximo en una vez:     69,723
  Primera compra:            23/09/2023
  Ultima compra:             12/09/2025
  Dias sin comprar:               8
  Frecuencia promedio:     cada 16 dias

  GERARDO PORRAS QUESADA
  Compras realizadas:            44
  Gasto total historico:      446,502
  Ticket promedio:             10,148
  Gasto maximo en una vez:     55,143
  Primera compra:            03/10/2023
  Ultima compra:             01/09/2025
  Dias sin comprar:              19
  Frecuencia promedio:     cada 16 dias

  VIRGINIA LOPEZ CALDERON
  Compras realizadas:            44
  Gasto total historico:      362,568
  Ticket promedio:              8,240
  Gasto maximo en una vez:     24,500
  Primera compra:            23/09/2023
  Ultima compra:             15/09/2025
  Dias sin comprar:               5
  Frecuencia promedio:     cada 16 dias

  DIDIER
  Compras realizadas:            43
  Gasto total historico:      492,650
  Ticket promedio:             11,457
  Gasto maximo en una vez:     67,000
  Primera compra:            30/09/2023
  Ultima compra:             30/08/2025
  Dias sin comprar:              21
  Frecuencia promedio:     cada 16 dias

  JORGE
  Compras realizadas:            43
  Gasto total historico:      284,901
  Ticket promedio:              6,626
  Gasto maximo en una vez:     32,200
  Primera compra:            02/10/2023
  Ultima compra:             17/09/2025
  Dias sin comprar:               3
  Frecuencia promedio:     cada 17 dias

  BRAYAN
  Compras realizadas:            43
  Gasto total historico:      290,310
  Ticket promedio:              6,751
  Gasto maximo en una vez:     32,000
  Primera compra:            06/01/2024
  Ultima compra:             17/09/2025

In [46]:
# ═══════════════════════════════DIAS Y MESES DE MAYOR VENTA
# Identificar patrones de cuando vende mas
# el negocio. Esto define:
# - Cuando tener mas stock disponible
# - Cuando programar pedidos a proveedores
# - Cuando necesitas mas personal disponible
# ══════════════════════════════════════════════════

print("ANALISIS DE DIAS Y MESES DE MAYOR VENTA")
print("=" * 65)

# ── POR DIA DE LA SEMANA ────────────────────────────
dias_orden = ['Monday','Tuesday','Wednesday',
              'Thursday','Friday','Saturday','Sunday']
dias_es    = {
    'Monday'   : 'Lunes',
    'Tuesday'  : 'Martes',
    'Wednesday': 'Miercoles',
    'Thursday' : 'Jueves',
    'Friday'   : 'Viernes',
    'Saturday' : 'Sabado',
    'Sunday'   : 'Domingo',
}

por_dia = df_facturas.groupby('dia_semana').agg(
    ventas_total    = ('total', 'sum'),
    facturas        = ('total', 'count'),
    ticket_promedio = ('total', 'mean'),
).reindex([d for d in dias_orden if d in df_facturas['dia_semana'].unique()])

venta_max_dia = por_dia['ventas_total'].max()

print(f"\nVENTAS POR DIA DE LA SEMANA:")
print(f"  {'Dia':<12} {'Ventas Total':>14} {'Facturas':>10} "
      f"{'Ticket Prom':>13} {'Intensidad':>12}")
print(f"  {'-'*65}")

for dia, row in por_dia.iterrows():
    nombre_dia = dias_es.get(dia, dia)
    barra = '|' * int(row['ventas_total'] / venta_max_dia * 20)
    print(f"  {nombre_dia:<12} "
          f"  {row['ventas_total']:>12,.0f} "
          f"  {int(row['facturas']):>8,} "
          f"  {row['ticket_promedio']:>11,.0f} "
          f"  {barra}")

mejor_dia = dias_es.get(por_dia['ventas_total'].idxmax(), '')
peor_dia  = dias_es.get(por_dia['ventas_total'].idxmin(), '')
print(f"\n  Mejor dia de ventas:  {mejor_dia}")
print(f"  Dia mas tranquilo:    {peor_dia}")

# ── POR QUINCENA (inicio vs fin de mes) ─────────────
df_facturas['quincena'] = df_facturas['fecha'].dt.day.apply(
    lambda d: 'Primera quincena (1-15)' if d <= 15 else 'Segunda quincena (16-31)'
)

por_quincena = df_facturas.groupby('quincena').agg(
    ventas_total    = ('total', 'sum'),
    facturas        = ('total', 'count'),
    ticket_promedio = ('total', 'mean'),
).reset_index()

print(f"\n\nVENTAS POR QUINCENA DEL MES:")
print(f"  {'Quincena':<28} {'Ventas Total':>14} {'Facturas':>10} {'Ticket Prom':>13}")
print(f"  {'-'*68}")
for _, row in por_quincena.iterrows():
    print(f"  {row['quincena']:<28} "
          f"  {row['ventas_total']:>12,.0f} "
          f"  {int(row['facturas']):>8,} "
          f"  {row['ticket_promedio']:>11,.0f}")

# ── POR MES DEL AÑO ─────────────────────────────────
meses_es = {1:'Enero',2:'Febrero',3:'Marzo',4:'Abril',
            5:'Mayo',6:'Junio',7:'Julio',8:'Agosto',
            9:'Septiembre',10:'Octubre',11:'Noviembre',12:'Diciembre'}

por_mes = df_facturas.groupby('mes').agg(
    ventas_total    = ('total', 'sum'),
    facturas        = ('total', 'count'),
    ticket_promedio = ('total', 'mean'),
).reset_index()

por_mes['mes_nombre'] = por_mes['mes'].map(meses_es)
venta_max_mes = por_mes['ventas_total'].max()

print(f"\n\nVENTAS POR MES DEL AÑO (historico acumulado):")
print(f"  {'Mes':<12} {'Ventas Total':>14} {'Facturas':>10} "
      f"{'Ticket Prom':>13} {'Intensidad':>12}")
print(f"  {'-'*65}")

por_mes_ord = por_mes.sort_values('mes')
for _, row in por_mes_ord.iterrows():
    barra = '|' * int(row['ventas_total'] / venta_max_mes * 20)
    print(f"  {row['mes_nombre']:<12} "
          f"  {row['ventas_total']:>12,.0f} "
          f"  {int(row['facturas']):>8,} "
          f"  {row['ticket_promedio']:>11,.0f} "
          f"  {barra}")

mejor_mes = por_mes.loc[por_mes['ventas_total'].idxmax(), 'mes_nombre']
peor_mes  = por_mes.loc[por_mes['ventas_total'].idxmin(), 'mes_nombre']

print(f"\n  Mejor mes historico:  {mejor_mes}")
print(f"  Mes mas tranquilo:    {peor_mes}")

# ── RESUMEN EJECUTIVO ────────────────────────────────
print(f"\n\nCONCLUSIONES PARA LA VICTORIA:")
print(f"  {'─'*60}")
print(f"  1. Programar pedidos a proveedores los dias previos")
print(f"     al mejor dia de ventas para garantizar stock.")
print(f"\n  2. La quincena con mas ventas define cuando")
print(f"     el cliente tiene mas liquidez para comprar.")
print(f"\n  3. Los meses de mayor venta historica son los")
print(f"     momentos para ejecutar promociones y ofertas.")
print(f"\n  4. Los meses tranquilos son para ordenar inventario,")
print(f"     negociar con proveedores y capacitarse.")

ANALISIS DE DIAS Y MESES DE MAYOR VENTA
=================================================================

VENTAS POR DIA DE LA SEMANA:
  Dia            Ventas Total   Facturas   Ticket Prom   Intensidad
  -----------------------------------------------------------------
  Lunes            26,395,430      2,851         9,258   ||||||||||||||
  Martes           33,528,212      2,795        11,996   ||||||||||||||||||
  Miercoles        32,654,974      2,645        12,346   ||||||||||||||||||
  Jueves           31,429,265      2,663        11,802   |||||||||||||||||
  Viernes          32,110,269      2,766        11,609   |||||||||||||||||
  Sabado           36,100,769      3,445        10,479   ||||||||||||||||||||

  Mejor dia de ventas:  Sabado
  Dia mas tranquilo:    Lunes


VENTAS POR QUINCENA DEL MES:
  Quincena                       Ventas Total   Facturas   Ticket Prom
  --------------------------------------------------------------------
  Primera quincena (1-15)          93,539,145      8,271        11,309
  Segunda quincena (16-31)         98,679,773      8,894        11,095


VENTAS POR MES DEL AÑO (historico acumulado):
  Mes            Ventas Total   Facturas   Ticket Prom   Intensidad
  -----------------------------------------------------------------
  Enero            17,238,502      1,524        11,311   ||||||||||||||||||||
  Febrero          16,417,587      1,328        12,363   |||||||||||||||||||
  Marzo            15,866,831      1,429        11,103   ||||||||||||||||||
  Abril            16,125,421      1,373        11,745   ||||||||||||||||||
  Mayo             16,013,003      1,494        10,718   ||||||||||||||||||
  Junio            16,010,573      1,359        11,781   ||||||||||||||||||
  Julio            16,710,416      1,530        10,922   |||||||||||||||||||
  Agosto           15,206,268      1,574         9,661   |||||||||||||||||
  Septiembre       16,755,536      1,610        10,407   |||||||||||||||||||
  Octubre          15,033,423      1,261        11,922   |||||||||||||||||
  Noviembre        14,388,739      1,226        11,736   ||||||||||||||||
  Diciembre        16,452,620      1,457        11,292   |||||||||||||||||||

  Mejor mes historico:  Enero
  Mes mas tranquilo:    Noviembre


CONCLUSIONES PARA LA VICTORIA:
  ────────────────────────────────────────────────────────────
  1. Programar pedidos a proveedores los dias previos
     al mejor dia de ventas para garantizar stock.

  2. La quincena con mas ventas define cuando
     el cliente tiene mas liquidez para comprar.

  3. Los meses de mayor venta historica son los
     momentos para ejecutar promociones y ofertas.

  4. Los meses tranquilos son para ordenar inventario,
     negociar con proveedores y capacitarse.

In [54]:
# ══════════════════════════ — PROVEEDORES CON CODIGOS EXACTOS
# Usando codigo de proveedor para evitar
# coincidencias incorrectas
# ══════════════════════════════════════════════════

# Codigos exactos confirmados
codigos_estrategicos = {
    'NAVEMAR'              : None,   # buscar por nombre
    'DISTRIBUIDORA XANDER' : 4,
    'GRUPO S Y S'          : None,
    'REPUESTOS MUNDIALES'  : None,
    'KINSEI'               : 223,
    'AUTO REPUESTOS AV DIEZ': 3,
    'GIGANTE'              : None,
}

print("PROVEEDORES ESTRATEGICOS — VERIFICACION FINAL")
print("=" * 60)

proveedores_validados = []

for nombre_key, codigo in codigos_estrategicos.items():

    if codigo:
        # Buscar por codigo exacto
        coincidencia = df_proveedores[
            df_proveedores['Código'] == codigo
        ]
    else:
        # Buscar por nombre
        coincidencia = df_proveedores[
            df_proveedores['Nombre comercial'].str.contains(
                nombre_key, na=False
            )
        ]

    if len(coincidencia) > 0:
        row = coincidencia.iloc[0]
        proveedores_validados.append({
            'key'    : nombre_key,
            'codigo' : row['Código'],
            'nombre' : row['Nombre comercial'],
        })
        print(f"  [{nombre_key}]")
        print(f"   Nombre oficial: {row['Nombre comercial']}")
        print(f"   Codigo:         {row['Código']}")
        print()
    else:
        print(f"  [{nombre_key}] — No encontrado, confirmar nombre")
        print()

print(f"Total proveedores estrategicos validados: {len(proveedores_validados)}")

PROVEEDORES ESTRATEGICOS — VERIFICACION FINAL
============================================================
  [NAVEMAR]
   Nombre oficial: NAVEMAR SOCIEDAD ANONIMA
   Codigo:         23

  [DISTRIBUIDORA XANDER]
   Nombre oficial: DISTRIBUIDORA XANDER DCRX SOCIEDAD ANONIMA
   Codigo:         4

  [GRUPO S Y S]
   Nombre oficial: GRUPO S Y S DIVISION AUTOMOTRIZ SOCIEDAD ANONIMA
   Codigo:         57

  [REPUESTOS MUNDIALES]
   Nombre oficial: REPUESTOS MUNDIALES SOCIEDAD ANONIMA
   Codigo:         29

  [KINSEI]
   Nombre oficial: KINSEI LIMITADA
   Codigo:         223

  [AUTO REPUESTOS AV DIEZ]
   Nombre oficial: AUTO REPUESTOS AV DIEZ SOCIEDAD ANONIMA
   Codigo:         3

  [GIGANTE]
   Nombre oficial: REPUESTOS GIGANTE SOCIEDAD ANONIMA
   Codigo:         15

Total proveedores estrategicos validados: 7

In [55]:
# ═════════════════════════════ — ANALISIS COMPLETO
# PROVEEDORES ESTRATEGICOS
# Version autónoma — no depende de celdas anteriores
# ══════════════════════════════════════════════════

import pandas as pd

print("ANALISIS DE PROVEEDORES ESTRATEGICOS")
print("Total Automotriz La Victoria")
print("=" * 70)

# Proveedores validados con sus nombres exactos del catalogo
proveedores_estrategicos = [
    'NAVEMAR',
    'DISTRIBUIDORA XANDER DCRX',
    'GRUPO S Y S',
    'REPUESTOS MUNDIALES',
    'KINSEI LIMITADA',
    'AUTO REPUESTOS AV DIEZ',
    'GIGANTE',
]

# Verificar columnas disponibles en articulos
print(f"\nColumnas en df_articulos:")
print(df_articulos.columns.tolist())

# Identificar columna de proveedor
col_prov = None
for col in df_articulos.columns:
    if 'PROVEEDOR' in str(col).upper() or 'PROV' in str(col).upper():
        col_prov = col
        print(f"\nColumna de proveedor encontrada: '{col_prov}'")
        break

if col_prov is None:
    print("\nNo hay columna de proveedor en articulos.")
    print("Analizando desde el catalogo de proveedores directamente.")

    # Mostrar los proveedores estrategicos del catalogo
    print(f"\n{'='*70}")
    print(f"PROVEEDORES ESTRATEGICOS — INFORMACION DEL CATALOGO")
    print(f"{'='*70}")

    for prov in proveedores_estrategicos:
        coincidencia = df_proveedores[
            df_proveedores['Nombre comercial'].str.upper().str.contains(
                prov.split()[0], na=False
            )
        ]
        if len(coincidencia) > 0:
            row = coincidencia.iloc[0]
            print(f"\n  {prov}")
            print(f"  {'─'*55}")
            for col in df_proveedores.columns:
                val = row[col]
                if pd.notna(val) and str(val).strip() not in ['', 'NAN', 'NONE']:
                    print(f"  {str(col):<25} {str(val)}")
        else:
            print(f"\n  {prov} — No encontrado en catalogo")

else:
    # Si hay columna de proveedor en articulos
    df_articulos[col_prov] = (
        df_articulos[col_prov].astype(str).str.upper().str.strip()
    )

    resumen = []

    for prov in proveedores_estrategicos:
        palabra_clave = prov.split()[0]

        df_prov = df_articulos[
            df_articulos[col_prov].str.contains(palabra_clave, na=False)
        ].copy()

        if len(df_prov) == 0:
            print(f"\n  {prov} — Sin articulos en catalogo")
            continue

        total       = len(df_prov)
        con_stock   = len(df_prov[df_prov['Inventario'] > 0])
        sin_stock   = len(df_prov[df_prov['Inventario'] == 0])
        margen_prom = df_prov['%Utilidad'].mean()
        precio_prom = df_prov['Precio venta'].mean()
        categorias  = df_prov['Línea'].nunique()
        valor_inv   = (df_prov['Inventario'] * df_prov['Costo neto']).sum()

        resumen.append({
            'Proveedor'  : prov,
            'Articulos'  : total,
            'Con stock'  : con_stock,
            'Sin stock'  : sin_stock,
            'Margen'     : margen_prom,
            'Precio prom': precio_prom,
            'Categorias' : categorias,
            'Valor inv'  : valor_inv,
        })

        print(f"\n{'='*70}")
        print(f"  {prov}")
        print(f"{'='*70}")
        print(f"  Articulos en catalogo:       {total:>8,}")
        print(f"  Con stock actual:            {con_stock:>8,}")
        print(f"  Sin stock (agotados):        {sin_stock:>8,}")
        print(f"  Categorias que surte:        {categorias:>8,}")
        print(f"  Margen promedio:             {margen_prom:>7.1f}%")
        print(f"  Precio promedio:             {precio_prom:>10,.0f}")
        print(f"  Valor en inventario:         {valor_inv:>10,.0f}")

        # Top 5 categorias
        cats = df_prov['Línea'].value_counts().head(5)
        print(f"\n  Categorias principales:")
        for cat, cnt in cats.items():
            print(f"    {cat:<35} {cnt:>4} articulos")

        # Top 5 por margen
        top5 = df_prov.nlargest(5, '%Utilidad')[
            ['Nombre','Precio venta','%Utilidad','Inventario']
        ]
        print(f"\n  Top 5 articulos por margen:")
        print(f"  {'Articulo':<48} {'Precio':>10} {'Margen':>8} {'Stock':>7}")
        print(f"  {'─'*76}")
        for _, row in top5.iterrows():
            nombre    = str(row['Nombre'])[:46]
            stock_txt = 'AGOTADO' if row['Inventario'] == 0 \
                        else str(int(row['Inventario']))
            print(f"  {nombre:<48} "
                  f"  {row['Precio venta']:>8,.0f} "
                  f"  {row['%Utilidad']:>6.1f}% "
                  f"  {stock_txt:>7}")

    # Ranking final si hay datos
    if resumen:
        df_res = pd.DataFrame(resumen)

        df_res['score'] = (
            (df_res['Articulos'] / df_res['Articulos'].max() * 0.35) +
            (df_res['Margen']    / df_res['Margen'].max()    * 0.40) +
            (df_res['Con stock'] / df_res['Con stock'].max() * 0.25)
        ).round(3)

        df_res = df_res.sort_values('score', ascending=False).reset_index(drop=True)

        print(f"\n\n{'='*70}")
        print(f"  RANKING FINAL — CON QUIEN EMPEZAR A COMPRAR")
        print(f"  Peso: Margen 40% | Articulos 35% | Stock disponible 25%")
        print(f"{'='*70}")
        print(f"\n  {'#':<4} {'Proveedor':<28} {'Arts':>6} {'Margen':>8} "
              f"{'Categ':>7} {'Score':>8}")
        print(f"  {'─'*65}")

        for i, row in df_res.iterrows():
            print(f"  {i+1:<4} {row['Proveedor']:<28} "
                  f"{int(row['Articulos']):>6,} "
                  f"{row['Margen']:>7.1f}% "
                  f"{int(row['Categorias']):>7} "
                  f"{row['score']:>8.3f}")

        print(f"\n  RECOMENDACION:")
        print(f"  Iniciar negociacion con los 3 primeros del ranking.")
        print(f"  Los 4 restantes se activan en las primeras 2 semanas.")

ANALISIS DE PROVEEDORES ESTRATEGICOS
Total Automotriz La Victoria
======================================================================

Columnas en df_articulos:
['Código', 'Cód. predeterminado', 'Nombre', 'Inv.Stock', 'Inventario', 'Precio venta', 'Estado', 'Cabys', 'Línea', 'Costo neto', '%Utilidad', '%Impuesto', 'Moneda', 'Ubicación', 'nivel_stock']

No hay columna de proveedor en articulos.
Analizando desde el catalogo de proveedores directamente.

======================================================================
PROVEEDORES ESTRATEGICOS — INFORMACION DEL CATALOGO
======================================================================

  NAVEMAR
  ───────────────────────────────────────────────────────
  Código                    23
  Nombre comercial          NAVEMAR SOCIEDAD ANONIMA
  Nombre fiscal             NAVEMAR SOCIEDAD ANONIMA
  Número identificación     3101035984
  Teléfonos                 2283-2430
  Estado                    Activo
  Límite crédito            200000.0
  Plazo crédito             30.0
  Fecha                     2020-03-12 00:00:00
  Facturación               Crédito

  DISTRIBUIDORA XANDER DCRX
  ───────────────────────────────────────────────────────
  Código                    4
  Nombre comercial          DISTRIBUIDORA XANDER DCRX SOCIEDAD ANONIMA
  Nombre fiscal             DISTRIBUIDORA XANDER DCRX SOCIEDAD ANONI
  Número identificación     3101668071
  Teléfonos                 27644770
  Estado                    Activo
  Límite crédito            100000.0
  Plazo crédito             30.0
  Fecha                     2020-01-12 00:00:00
  Facturación               Crédito

  GRUPO S Y S
  ───────────────────────────────────────────────────────
  Código                    40
  Nombre comercial          GRUPO R-LAJCR SOCIEDAD ANONIMA
  Nombre fiscal             GRUPO R-LAJCR SOCIEDAD ANONIMA
  Número identificación     3101599853
  Estado                    Activo
  Límite crédito            300000.0
  Plazo crédito             30.0
  Fecha                     2020-04-29 00:00:00
  Facturación               Crédito

  REPUESTOS MUNDIALES
  ───────────────────────────────────────────────────────
  Código                    1
  Nombre comercial          REPUESTOS SERRANOS SOCIEDAD ANONIMA
  Nombre fiscal             REPUESTOS SERRANOS SOCIEDAD ANONIMA
  Número identificación     3101581058
  Teléfonos                 24734422
  Estado                    Inactivo
  Límite crédito            500000.0
  Plazo crédito             30.0
  Fecha                     2020-01-14 00:00:00
  Facturación               Crédito

  KINSEI LIMITADA
  ───────────────────────────────────────────────────────
  Código                    223
  Nombre comercial          KINSEI LIMITADA
  Nombre fiscal             KINSEI LIMITADA
  Número identificación     3102129408
  Teléfonos                 22570268
  Dirección                 Centro ColÃ³n, 25 Norte S.J.C.R.
  Correo electrónico        fekinseicobrar@gmail.com
  Estado                    Activo
  Límite crédito            0.0
  Plazo crédito             0.0
  Fecha                     2025-01-09 00:00:00
  Facturación               Contado

  AUTO REPUESTOS AV DIEZ
  ───────────────────────────────────────────────────────
  Código                    3
  Nombre comercial          AUTO REPUESTOS AV DIEZ SOCIEDAD ANONIMA
  Nombre fiscal             AUTO REPUESTOS AV DIEZ SOCIEDAD ANONIMA
  Número identificación     3101081554
  Teléfonos                 27101300
  Dirección                 GUAPILES
  Estado                    Activo
  Límite crédito            0.0
  Plazo crédito             0.0
  Fecha                     2020-01-12 00:00:00
  Facturación               Contado

  GIGANTE
  ───────────────────────────────────────────────────────
  Código                    15
  Nombre comercial          REPUESTOS GIGANTE SOCIEDAD ANONIMA
  Nombre fiscal             REPUESTOS GIGANTE SOCIEDAD ANONIMA
  Número identificación     3101156677
  Estado                    Activo
  Límite crédito            0.0
  Plazo crédito             0.0
  Fecha                     2020-02-07 00:00:00
  Facturación               Contado